#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/America
## deinstalls tiles covering America

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/w030s60
git submodule deinit Objects/w040s10
git submodule deinit Objects/w040s20
git submodule deinit Objects/w040s40
git submodule deinit Objects/w040s60
git submodule deinit Objects/w050n00
git submodule deinit Objects/w050n80
git submodule deinit Objects/w050s10
git submodule deinit Objects/w050s20
git submodule deinit Objects/w050s30
git submodule deinit Objects/w050s60
git submodule deinit Objects/w060n00
git submodule deinit Objects/w060n10
git submodule deinit Objects/w060n40
git submodule deinit Objects/w060n50
git submodule deinit Objects/w060n60
git submodule deinit Objects/w060n80
git submodule deinit Objects/w060s10
git submodule deinit Objects/w060s20
git submodule deinit Objects/w060s30
git submodule deinit Objects/w060s40
git submodule deinit Objects/w060s60
git submodule deinit Objects/w070n00
git submodule deinit Objects/w070n10
git submodule deinit Objects/w070n30
git submodule deinit Objects/w070n40
git submodule deinit Objects/w070n50
git submodule deinit Objects/w070n60
git submodule deinit Objects/w070n70
git submodule deinit Objects/w070n80
git submodule deinit Objects/w070s10
git submodule deinit Objects/w070s20
git submodule deinit Objects/w070s30
git submodule deinit Objects/w070s40
git submodule deinit Objects/w070s50
git submodule deinit Objects/w070s60
git submodule deinit Objects/w080n00
git submodule deinit Objects/w080n10
git submodule deinit Objects/w080n20
git submodule deinit Objects/w080n30
git submodule deinit Objects/w080n40
git submodule deinit Objects/w080n50
git submodule deinit Objects/w080n60
git submodule deinit Objects/w080n70
git submodule deinit Objects/w080n80
git submodule deinit Objects/w080s10
git submodule deinit Objects/w080s20
git submodule deinit Objects/w080s30
git submodule deinit Objects/w080s40
git submodule deinit Objects/w080s50
git submodule deinit Objects/w080s60
git submodule deinit Objects/w090n00
git submodule deinit Objects/w090n10
git submodule deinit Objects/w090n20
git submodule deinit Objects/w090n30
git submodule deinit Objects/w090n40
git submodule deinit Objects/w090n50
git submodule deinit Objects/w090n60
git submodule deinit Objects/w090n70
git submodule deinit Objects/w090n80
git submodule deinit Objects/w090s10
git submodule deinit Objects/w090s20
git submodule deinit Objects/w090s30
git submodule deinit Objects/w090s40
git submodule deinit Objects/w100n00
git submodule deinit Objects/w100n10
git submodule deinit Objects/w100n20
git submodule deinit Objects/w100n30
git submodule deinit Objects/w100n40
git submodule deinit Objects/w100n50
git submodule deinit Objects/w100n60
git submodule deinit Objects/w100n70
git submodule deinit Objects/w100n80
git submodule deinit Objects/w100s10
git submodule deinit Objects/w110n10
git submodule deinit Objects/w110n20
git submodule deinit Objects/w110n30
git submodule deinit Objects/w110n40
git submodule deinit Objects/w110n50
git submodule deinit Objects/w110n60
git submodule deinit Objects/w110n70
git submodule deinit Objects/w110n80
git submodule deinit Objects/w120n10
git submodule deinit Objects/w120n20
git submodule deinit Objects/w120n30
git submodule deinit Objects/w120n40
git submodule deinit Objects/w120n50
git submodule deinit Objects/w120n60
git submodule deinit Objects/w120n70
git submodule deinit Objects/w120n80
git submodule deinit Objects/w130n30
git submodule deinit Objects/w130n40
git submodule deinit Objects/w130n50
git submodule deinit Objects/w130n60
git submodule deinit Objects/w130n70
git submodule deinit Objects/w130n80
git submodule deinit Objects/w140n50
git submodule deinit Objects/w140n60
git submodule deinit Objects/w140n70
git submodule deinit Objects/w150n10
git submodule deinit Objects/w150n50
git submodule deinit Objects/w150n60
git submodule deinit Objects/w160n10
git submodule deinit Objects/w160n20
git submodule deinit Objects/w160n50
git submodule deinit Objects/w160n60
git submodule deinit Objects/w170n10
git submodule deinit Objects/w170n20
git submodule deinit Objects/w170n50
git submodule deinit Objects/w170n60
git submodule deinit Objects/w180n20
git submodule deinit Objects/w180n50
git submodule deinit Objects/w180n60
git submodule deinit Terrain/w030s60
git submodule deinit Terrain/w040s10
git submodule deinit Terrain/w040s20
git submodule deinit Terrain/w040s40
git submodule deinit Terrain/w040s60
git submodule deinit Terrain/w050n00
git submodule deinit Terrain/w050n80
git submodule deinit Terrain/w050s10
git submodule deinit Terrain/w050s20
git submodule deinit Terrain/w050s30
git submodule deinit Terrain/w050s60
git submodule deinit Terrain/w060n00
git submodule deinit Terrain/w060n10
git submodule deinit Terrain/w060n40
git submodule deinit Terrain/w060n50
git submodule deinit Terrain/w060n60
git submodule deinit Terrain/w060n80
git submodule deinit Terrain/w060s10
git submodule deinit Terrain/w060s20
git submodule deinit Terrain/w060s30
git submodule deinit Terrain/w060s40
git submodule deinit Terrain/w060s60
git submodule deinit Terrain/w070n00
git submodule deinit Terrain/w070n10
git submodule deinit Terrain/w070n30
git submodule deinit Terrain/w070n40
git submodule deinit Terrain/w070n50
git submodule deinit Terrain/w070n60
git submodule deinit Terrain/w070n70
git submodule deinit Terrain/w070n80
git submodule deinit Terrain/w070s10
git submodule deinit Terrain/w070s20
git submodule deinit Terrain/w070s30
git submodule deinit Terrain/w070s40
git submodule deinit Terrain/w070s50
git submodule deinit Terrain/w070s60
git submodule deinit Terrain/w080n00
git submodule deinit Terrain/w080n10
git submodule deinit Terrain/w080n20
git submodule deinit Terrain/w080n30
git submodule deinit Terrain/w080n40
git submodule deinit Terrain/w080n50
git submodule deinit Terrain/w080n60
git submodule deinit Terrain/w080n70
git submodule deinit Terrain/w080n80
git submodule deinit Terrain/w080s10
git submodule deinit Terrain/w080s20
git submodule deinit Terrain/w080s30
git submodule deinit Terrain/w080s40
git submodule deinit Terrain/w080s50
git submodule deinit Terrain/w080s60
git submodule deinit Terrain/w090n00
git submodule deinit Terrain/w090n10
git submodule deinit Terrain/w090n20
git submodule deinit Terrain/w090n30
git submodule deinit Terrain/w090n40
git submodule deinit Terrain/w090n50
git submodule deinit Terrain/w090n60
git submodule deinit Terrain/w090n70
git submodule deinit Terrain/w090n80
git submodule deinit Terrain/w090s10
git submodule deinit Terrain/w090s20
git submodule deinit Terrain/w090s30
git submodule deinit Terrain/w090s40
git submodule deinit Terrain/w100n00
git submodule deinit Terrain/w100n10
git submodule deinit Terrain/w100n20
git submodule deinit Terrain/w100n30
git submodule deinit Terrain/w100n40
git submodule deinit Terrain/w100n50
git submodule deinit Terrain/w100n60
git submodule deinit Terrain/w100n70
git submodule deinit Terrain/w100n80
git submodule deinit Terrain/w100s10
git submodule deinit Terrain/w110n10
git submodule deinit Terrain/w110n20
git submodule deinit Terrain/w110n30
git submodule deinit Terrain/w110n40
git submodule deinit Terrain/w110n50
git submodule deinit Terrain/w110n60
git submodule deinit Terrain/w110n70
git submodule deinit Terrain/w110n80
git submodule deinit Terrain/w120n10
git submodule deinit Terrain/w120n20
git submodule deinit Terrain/w120n30
git submodule deinit Terrain/w120n40
git submodule deinit Terrain/w120n50
git submodule deinit Terrain/w120n60
git submodule deinit Terrain/w120n70
git submodule deinit Terrain/w120n80
git submodule deinit Terrain/w130n30
git submodule deinit Terrain/w130n40
git submodule deinit Terrain/w130n50
git submodule deinit Terrain/w130n60
git submodule deinit Terrain/w130n70
git submodule deinit Terrain/w130n80
git submodule deinit Terrain/w140n50
git submodule deinit Terrain/w140n60
git submodule deinit Terrain/w140n70
git submodule deinit Terrain/w150n10
git submodule deinit Terrain/w150n50
git submodule deinit Terrain/w150n60
git submodule deinit Terrain/w160n10
git submodule deinit Terrain/w160n20
git submodule deinit Terrain/w160n50
git submodule deinit Terrain/w160n60
git submodule deinit Terrain/w170n10
git submodule deinit Terrain/w170n20
git submodule deinit Terrain/w170n50
git submodule deinit Terrain/w170n60
git submodule deinit Terrain/w180n20
git submodule deinit Terrain/w180n50
git submodule deinit Terrain/w180n60
 
git submodule update --progress Objects/w030s60
git submodule update --progress Objects/w040s10
git submodule update --progress Objects/w040s20
git submodule update --progress Objects/w040s40
git submodule update --progress Objects/w040s60
git submodule update --progress Objects/w050n00
git submodule update --progress Objects/w050n80
git submodule update --progress Objects/w050s10
git submodule update --progress Objects/w050s20
git submodule update --progress Objects/w050s30
git submodule update --progress Objects/w050s60
git submodule update --progress Objects/w060n00
git submodule update --progress Objects/w060n10
git submodule update --progress Objects/w060n40
git submodule update --progress Objects/w060n50
git submodule update --progress Objects/w060n60
git submodule update --progress Objects/w060n80
git submodule update --progress Objects/w060s10
git submodule update --progress Objects/w060s20
git submodule update --progress Objects/w060s30
git submodule update --progress Objects/w060s40
git submodule update --progress Objects/w060s60
git submodule update --progress Objects/w070n00
git submodule update --progress Objects/w070n10
git submodule update --progress Objects/w070n30
git submodule update --progress Objects/w070n40
git submodule update --progress Objects/w070n50
git submodule update --progress Objects/w070n60
git submodule update --progress Objects/w070n70
git submodule update --progress Objects/w070n80
git submodule update --progress Objects/w070s10
git submodule update --progress Objects/w070s20
git submodule update --progress Objects/w070s30
git submodule update --progress Objects/w070s40
git submodule update --progress Objects/w070s50
git submodule update --progress Objects/w070s60
git submodule update --progress Objects/w080n00
git submodule update --progress Objects/w080n10
git submodule update --progress Objects/w080n20
git submodule update --progress Objects/w080n30
git submodule update --progress Objects/w080n40
git submodule update --progress Objects/w080n50
git submodule update --progress Objects/w080n60
git submodule update --progress Objects/w080n70
git submodule update --progress Objects/w080n80
git submodule update --progress Objects/w080s10
git submodule update --progress Objects/w080s20
git submodule update --progress Objects/w080s30
git submodule update --progress Objects/w080s40
git submodule update --progress Objects/w080s50
git submodule update --progress Objects/w080s60
git submodule update --progress Objects/w090n00
git submodule update --progress Objects/w090n10
git submodule update --progress Objects/w090n20
git submodule update --progress Objects/w090n30
git submodule update --progress Objects/w090n40
git submodule update --progress Objects/w090n50
git submodule update --progress Objects/w090n60
git submodule update --progress Objects/w090n70
git submodule update --progress Objects/w090n80
git submodule update --progress Objects/w090s10
git submodule update --progress Objects/w090s20
git submodule update --progress Objects/w090s30
git submodule update --progress Objects/w090s40
git submodule update --progress Objects/w100n00
git submodule update --progress Objects/w100n10
git submodule update --progress Objects/w100n20
git submodule update --progress Objects/w100n30
git submodule update --progress Objects/w100n40
git submodule update --progress Objects/w100n50
git submodule update --progress Objects/w100n60
git submodule update --progress Objects/w100n70
git submodule update --progress Objects/w100n80
git submodule update --progress Objects/w100s10
git submodule update --progress Objects/w110n10
git submodule update --progress Objects/w110n20
git submodule update --progress Objects/w110n30
git submodule update --progress Objects/w110n40
git submodule update --progress Objects/w110n50
git submodule update --progress Objects/w110n60
git submodule update --progress Objects/w110n70
git submodule update --progress Objects/w110n80
git submodule update --progress Objects/w120n10
git submodule update --progress Objects/w120n20
git submodule update --progress Objects/w120n30
git submodule update --progress Objects/w120n40
git submodule update --progress Objects/w120n50
git submodule update --progress Objects/w120n60
git submodule update --progress Objects/w120n70
git submodule update --progress Objects/w120n80
git submodule update --progress Objects/w130n30
git submodule update --progress Objects/w130n40
git submodule update --progress Objects/w130n50
git submodule update --progress Objects/w130n60
git submodule update --progress Objects/w130n70
git submodule update --progress Objects/w130n80
git submodule update --progress Objects/w140n50
git submodule update --progress Objects/w140n60
git submodule update --progress Objects/w140n70
git submodule update --progress Objects/w150n10
git submodule update --progress Objects/w150n50
git submodule update --progress Objects/w150n60
git submodule update --progress Objects/w160n10
git submodule update --progress Objects/w160n20
git submodule update --progress Objects/w160n50
git submodule update --progress Objects/w160n60
git submodule update --progress Objects/w170n10
git submodule update --progress Objects/w170n20
git submodule update --progress Objects/w170n50
git submodule update --progress Objects/w170n60
git submodule update --progress Objects/w180n20
git submodule update --progress Objects/w180n50
git submodule update --progress Objects/w180n60
git submodule update --progress Terrain/w030s60
git submodule update --progress Terrain/w040s10
git submodule update --progress Terrain/w040s20
git submodule update --progress Terrain/w040s40
git submodule update --progress Terrain/w040s60
git submodule update --progress Terrain/w050n00
git submodule update --progress Terrain/w050n80
git submodule update --progress Terrain/w050s10
git submodule update --progress Terrain/w050s20
git submodule update --progress Terrain/w050s30
git submodule update --progress Terrain/w050s60
git submodule update --progress Terrain/w060n00
git submodule update --progress Terrain/w060n10
git submodule update --progress Terrain/w060n40
git submodule update --progress Terrain/w060n50
git submodule update --progress Terrain/w060n60
git submodule update --progress Terrain/w060n80
git submodule update --progress Terrain/w060s10
git submodule update --progress Terrain/w060s20
git submodule update --progress Terrain/w060s30
git submodule update --progress Terrain/w060s40
git submodule update --progress Terrain/w060s60
git submodule update --progress Terrain/w070n00
git submodule update --progress Terrain/w070n10
git submodule update --progress Terrain/w070n30
git submodule update --progress Terrain/w070n40
git submodule update --progress Terrain/w070n50
git submodule update --progress Terrain/w070n60
git submodule update --progress Terrain/w070n70
git submodule update --progress Terrain/w070n80
git submodule update --progress Terrain/w070s10
git submodule update --progress Terrain/w070s20
git submodule update --progress Terrain/w070s30
git submodule update --progress Terrain/w070s40
git submodule update --progress Terrain/w070s50
git submodule update --progress Terrain/w070s60
git submodule update --progress Terrain/w080n00
git submodule update --progress Terrain/w080n10
git submodule update --progress Terrain/w080n20
git submodule update --progress Terrain/w080n30
git submodule update --progress Terrain/w080n40
git submodule update --progress Terrain/w080n50
git submodule update --progress Terrain/w080n60
git submodule update --progress Terrain/w080n70
git submodule update --progress Terrain/w080n80
git submodule update --progress Terrain/w080s10
git submodule update --progress Terrain/w080s20
git submodule update --progress Terrain/w080s30
git submodule update --progress Terrain/w080s40
git submodule update --progress Terrain/w080s50
git submodule update --progress Terrain/w080s60
git submodule update --progress Terrain/w090n00
git submodule update --progress Terrain/w090n10
git submodule update --progress Terrain/w090n20
git submodule update --progress Terrain/w090n30
git submodule update --progress Terrain/w090n40
git submodule update --progress Terrain/w090n50
git submodule update --progress Terrain/w090n60
git submodule update --progress Terrain/w090n70
git submodule update --progress Terrain/w090n80
git submodule update --progress Terrain/w090s10
git submodule update --progress Terrain/w090s20
git submodule update --progress Terrain/w090s30
git submodule update --progress Terrain/w090s40
git submodule update --progress Terrain/w100n00
git submodule update --progress Terrain/w100n10
git submodule update --progress Terrain/w100n20
git submodule update --progress Terrain/w100n30
git submodule update --progress Terrain/w100n40
git submodule update --progress Terrain/w100n50
git submodule update --progress Terrain/w100n60
git submodule update --progress Terrain/w100n70
git submodule update --progress Terrain/w100n80
git submodule update --progress Terrain/w100s10
git submodule update --progress Terrain/w110n10
git submodule update --progress Terrain/w110n20
git submodule update --progress Terrain/w110n30
git submodule update --progress Terrain/w110n40
git submodule update --progress Terrain/w110n50
git submodule update --progress Terrain/w110n60
git submodule update --progress Terrain/w110n70
git submodule update --progress Terrain/w110n80
git submodule update --progress Terrain/w120n10
git submodule update --progress Terrain/w120n20
git submodule update --progress Terrain/w120n30
git submodule update --progress Terrain/w120n40
git submodule update --progress Terrain/w120n50
git submodule update --progress Terrain/w120n60
git submodule update --progress Terrain/w120n70
git submodule update --progress Terrain/w120n80
git submodule update --progress Terrain/w130n30
git submodule update --progress Terrain/w130n40
git submodule update --progress Terrain/w130n50
git submodule update --progress Terrain/w130n60
git submodule update --progress Terrain/w130n70
git submodule update --progress Terrain/w130n80
git submodule update --progress Terrain/w140n50
git submodule update --progress Terrain/w140n60
git submodule update --progress Terrain/w140n70
git submodule update --progress Terrain/w150n10
git submodule update --progress Terrain/w150n50
git submodule update --progress Terrain/w150n60
git submodule update --progress Terrain/w160n10
git submodule update --progress Terrain/w160n20
git submodule update --progress Terrain/w160n50
git submodule update --progress Terrain/w160n60
git submodule update --progress Terrain/w170n10
git submodule update --progress Terrain/w170n20
git submodule update --progress Terrain/w170n50
git submodule update --progress Terrain/w170n60
git submodule update --progress Terrain/w180n20
git submodule update --progress Terrain/w180n50
git submodule update --progress Terrain/w180n60
