#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/Europe
## deinstalls tiles covering Europe

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (deinitializing and updating both Terrain and Objects)

git submodule deinit Objects/w030n10
git submodule deinit Objects/w030n30
git submodule deinit Objects/w030n60
git submodule deinit Objects/w020n30
git submodule deinit Objects/w020n50
git submodule deinit Objects/w020n60
git submodule deinit Objects/w020n70
git submodule deinit Objects/w010n30
git submodule deinit Objects/w010n40
git submodule deinit Objects/w010n50
git submodule deinit Objects/w010n60
git submodule deinit Objects/w010n70
git submodule deinit Objects/e000n30
git submodule deinit Objects/e000n40
git submodule deinit Objects/e000n50
git submodule deinit Objects/e000n60
git submodule deinit Objects/e000n70
git submodule deinit Objects/e010n30
git submodule deinit Objects/e010n40
git submodule deinit Objects/e010n50
git submodule deinit Objects/e010n60
git submodule deinit Objects/e010n70
git submodule deinit Objects/e020n30
git submodule deinit Objects/e020n40
git submodule deinit Objects/e020n50
git submodule deinit Objects/e020n60
git submodule deinit Objects/e020n70
git submodule deinit Objects/e030n30
git submodule deinit Objects/e030n40
git submodule deinit Objects/e030n50
git submodule deinit Objects/e030n60
git submodule deinit Objects/e030n70
git submodule deinit Objects/e040n40
git submodule deinit Objects/e040n50
git submodule deinit Objects/e040n60
git submodule deinit Objects/e040n70
git submodule deinit Objects/e040n80
git submodule deinit Objects/e050n40
git submodule deinit Objects/e050n50
git submodule deinit Objects/e050n60
git submodule deinit Objects/e050n70
git submodule deinit Objects/e050n80
git submodule deinit Terrain/w030n10
git submodule deinit Terrain/w030n30
git submodule deinit Terrain/w030n60
git submodule deinit Terrain/w020n30
git submodule deinit Terrain/w020n50
git submodule deinit Terrain/w020n60
git submodule deinit Terrain/w020n70
git submodule deinit Terrain/w010n30
git submodule deinit Terrain/w010n40
git submodule deinit Terrain/w010n50
git submodule deinit Terrain/w010n60
git submodule deinit Terrain/w010n70
git submodule deinit Terrain/e000n30
git submodule deinit Terrain/e000n40
git submodule deinit Terrain/e000n50
git submodule deinit Terrain/e000n60
git submodule deinit Terrain/e000n70
git submodule deinit Terrain/e010n30
git submodule deinit Terrain/e010n40
git submodule deinit Terrain/e010n50
git submodule deinit Terrain/e010n60
git submodule deinit Terrain/e010n70
git submodule deinit Terrain/e020n30
git submodule deinit Terrain/e020n40
git submodule deinit Terrain/e020n50
git submodule deinit Terrain/e020n60
git submodule deinit Terrain/e020n70
git submodule deinit Terrain/e030n30
git submodule deinit Terrain/e030n40
git submodule deinit Terrain/e030n50
git submodule deinit Terrain/e030n60
git submodule deinit Terrain/e030n70
git submodule deinit Terrain/e040n40
git submodule deinit Terrain/e040n50
git submodule deinit Terrain/e040n60
git submodule deinit Terrain/e040n70
git submodule deinit Terrain/e040n80
git submodule deinit Terrain/e050n40
git submodule deinit Terrain/e050n50
git submodule deinit Terrain/e050n60
git submodule deinit Terrain/e050n70
git submodule deinit Terrain/e050n80

git submodule update Objects/w030n10
git submodule update Objects/w030n30
git submodule update Objects/w030n60
git submodule update Objects/w020n30
git submodule update Objects/w020n50
git submodule update Objects/w020n60
git submodule update Objects/w020n70
git submodule update Objects/w010n30
git submodule update Objects/w010n40
git submodule update Objects/w010n50
git submodule update Objects/w010n60
git submodule update Objects/w010n70
git submodule update Objects/e000n30
git submodule update Objects/e000n40
git submodule update Objects/e000n50
git submodule update Objects/e000n60
git submodule update Objects/e000n70
git submodule update Objects/e010n30
git submodule update Objects/e010n40
git submodule update Objects/e010n50
git submodule update Objects/e010n60
git submodule update Objects/e010n70
git submodule update Objects/e020n30
git submodule update Objects/e020n40
git submodule update Objects/e020n50
git submodule update Objects/e020n60
git submodule update Objects/e020n70
git submodule update Objects/e030n30
git submodule update Objects/e030n40
git submodule update Objects/e030n50
git submodule update Objects/e030n60
git submodule update Objects/e030n70
git submodule update Objects/e040n40
git submodule update Objects/e040n50
git submodule update Objects/e040n60
git submodule update Objects/e040n70
git submodule update Objects/e040n80
git submodule update Objects/e050n40
git submodule update Objects/e050n50
git submodule update Objects/e050n60
git submodule update Objects/e050n70
git submodule update Objects/e050n80
git submodule update Terrain/w030n10
git submodule update Terrain/w030n30
git submodule update Terrain/w030n60
git submodule update Terrain/w020n30
git submodule update Terrain/w020n50
git submodule update Terrain/w020n60
git submodule update Terrain/w020n70
git submodule update Terrain/w010n30
git submodule update Terrain/w010n40
git submodule update Terrain/w010n50
git submodule update Terrain/w010n60
git submodule update Terrain/w010n70
git submodule update Terrain/e000n30
git submodule update Terrain/e000n40
git submodule update Terrain/e000n50
git submodule update Terrain/e000n60
git submodule update Terrain/e000n70
git submodule update Terrain/e010n30
git submodule update Terrain/e010n40
git submodule update Terrain/e010n50
git submodule update Terrain/e010n60
git submodule update Terrain/e010n70
git submodule update Terrain/e020n30
git submodule update Terrain/e020n40
git submodule update Terrain/e020n50
git submodule update Terrain/e020n60
git submodule update Terrain/e020n70
git submodule update Terrain/e030n30
git submodule update Terrain/e030n40
git submodule update Terrain/e030n50
git submodule update Terrain/e030n60
git submodule update Terrain/e030n70
git submodule update Terrain/e040n40
git submodule update Terrain/e040n50
git submodule update Terrain/e040n60
git submodule update Terrain/e040n70
git submodule update Terrain/e040n80
git submodule update Terrain/e050n40
git submodule update Terrain/e050n50
git submodule update Terrain/e050n60
git submodule update Terrain/e050n70
git submodule update Terrain/e050n80
