#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/India
## deinstalls tiles covering India

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (deinitializing and updating both Terrain and Objects)

git submodule deinit Objects/e060n20
git submodule deinit Objects/e070n30
git submodule deinit Objects/e070n20
git submodule deinit Objects/e070n10
git submodule deinit Objects/e070n00
git submodule deinit Objects/e070s10
git submodule deinit Objects/e080n20
git submodule deinit Objects/e080n10
git submodule deinit Objects/e080n00
git submodule deinit Terrain/e060n20
git submodule deinit Terrain/e070n30
git submodule deinit Terrain/e070n20
git submodule deinit Terrain/e070n10
git submodule deinit Terrain/e070n00
git submodule deinit Terrain/e070s10
git submodule deinit Terrain/e080n20
git submodule deinit Terrain/e080n10
git submodule deinit Terrain/e080n00

git submodule update --progress Objects/e060n20
git submodule update --progress Objects/e070n30
git submodule update --progress Objects/e070n20
git submodule update --progress Objects/e070n10
git submodule update --progress Objects/e070n00
git submodule update --progress Objects/e070s10
git submodule update --progress Objects/e080n20
git submodule update --progress Objects/e080n10
git submodule update --progress Objects/e080n00
git submodule update --progress Terrain/e060n20
git submodule update --progress Terrain/e070n30
git submodule update --progress Terrain/e070n20
git submodule update --progress Terrain/e070n10
git submodule update --progress Terrain/e070n00
git submodule update --progress Terrain/e070s10
git submodule update --progress Terrain/e080n20
git submodule update --progress Terrain/e080n10
git submodule update --progress Terrain/e080n00
