#!/bin/sh

## USAGE EXAMPLE
##
## deinsall/lat-s30
## deinsalls tiles covering lat-s30

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e010s30
git submodule deinit Objects/e020s30
git submodule deinit Objects/e030s30
git submodule deinit Objects/e040s30
git submodule deinit Objects/e050s30
git submodule deinit Objects/e110s30
git submodule deinit Objects/e120s30
git submodule deinit Objects/e130s30
git submodule deinit Objects/e140s30
git submodule deinit Objects/e150s30
git submodule deinit Objects/e160s30
git submodule deinit Objects/e170s30
git submodule deinit Objects/w030s30
git submodule deinit Objects/w050s30
git submodule deinit Objects/w060s30
git submodule deinit Objects/w070s30
git submodule deinit Objects/w080s30
git submodule deinit Objects/w090s30
git submodule deinit Objects/w110s30
git submodule deinit Objects/w130s30
git submodule deinit Objects/w140s30
git submodule deinit Objects/w150s30
git submodule deinit Objects/w160s30
git submodule deinit Objects/w180s30
git submodule deinit Terrain/e010s30
git submodule deinit Terrain/e020s30
git submodule deinit Terrain/e030s30
git submodule deinit Terrain/e040s30
git submodule deinit Terrain/e050s30
git submodule deinit Terrain/e110s30
git submodule deinit Terrain/e120s30
git submodule deinit Terrain/e130s30
git submodule deinit Terrain/e140s30
git submodule deinit Terrain/e150s30
git submodule deinit Terrain/e160s30
git submodule deinit Terrain/e170s30
git submodule deinit Terrain/w030s30
git submodule deinit Terrain/w050s30
git submodule deinit Terrain/w060s30
git submodule deinit Terrain/w070s30
git submodule deinit Terrain/w080s30
git submodule deinit Terrain/w090s30
git submodule deinit Terrain/w110s30
git submodule deinit Terrain/w130s30
git submodule deinit Terrain/w140s30
git submodule deinit Terrain/w150s30
git submodule deinit Terrain/w160s30
git submodule deinit Terrain/w180s30
git submodule update --progress Objects/e010s30
git submodule update --progress Objects/e020s30
git submodule update --progress Objects/e030s30
git submodule update --progress Objects/e040s30
git submodule update --progress Objects/e050s30
git submodule update --progress Objects/e110s30
git submodule update --progress Objects/e120s30
git submodule update --progress Objects/e130s30
git submodule update --progress Objects/e140s30
git submodule update --progress Objects/e150s30
git submodule update --progress Objects/e160s30
git submodule update --progress Objects/e170s30
git submodule update --progress Objects/w030s30
git submodule update --progress Objects/w050s30
git submodule update --progress Objects/w060s30
git submodule update --progress Objects/w070s30
git submodule update --progress Objects/w080s30
git submodule update --progress Objects/w090s30
git submodule update --progress Objects/w110s30
git submodule update --progress Objects/w130s30
git submodule update --progress Objects/w140s30
git submodule update --progress Objects/w150s30
git submodule update --progress Objects/w160s30
git submodule update --progress Objects/w180s30
git submodule update --progress Terrain/e010s30
git submodule update --progress Terrain/e020s30
git submodule update --progress Terrain/e030s30
git submodule update --progress Terrain/e040s30
git submodule update --progress Terrain/e050s30
git submodule update --progress Terrain/e110s30
git submodule update --progress Terrain/e120s30
git submodule update --progress Terrain/e130s30
git submodule update --progress Terrain/e140s30
git submodule update --progress Terrain/e150s30
git submodule update --progress Terrain/e160s30
git submodule update --progress Terrain/e170s30
git submodule update --progress Terrain/w030s30
git submodule update --progress Terrain/w050s30
git submodule update --progress Terrain/w060s30
git submodule update --progress Terrain/w070s30
git submodule update --progress Terrain/w080s30
git submodule update --progress Terrain/w090s30
git submodule update --progress Terrain/w110s30
git submodule update --progress Terrain/w130s30
git submodule update --progress Terrain/w140s30
git submodule update --progress Terrain/w150s30
git submodule update --progress Terrain/w160s30
git submodule update --progress Terrain/w180s30

