#!/bin/sh

## USAGE EXAMPLE
##
## deinsall/lat-s40
## deinsalls tiles covering lat-s40

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e010s40
git submodule deinit Objects/e020s40
git submodule deinit Objects/e030s40
git submodule deinit Objects/e070s40
git submodule deinit Objects/e110s40
git submodule deinit Objects/e120s40
git submodule deinit Objects/e130s40
git submodule deinit Objects/e140s40
git submodule deinit Objects/e150s40
git submodule deinit Objects/e170s40
git submodule deinit Objects/w020s40
git submodule deinit Objects/w040s40
git submodule deinit Objects/w060s40
git submodule deinit Objects/w070s40
git submodule deinit Objects/w080s40
git submodule deinit Objects/w090s40
git submodule deinit Objects/w180s40
git submodule deinit Terrain/e010s40
git submodule deinit Terrain/e020s40
git submodule deinit Terrain/e030s40
git submodule deinit Terrain/e070s40
git submodule deinit Terrain/e110s40
git submodule deinit Terrain/e120s40
git submodule deinit Terrain/e130s40
git submodule deinit Terrain/e140s40
git submodule deinit Terrain/e150s40
git submodule deinit Terrain/e170s40
git submodule deinit Terrain/w020s40
git submodule deinit Terrain/w040s40
git submodule deinit Terrain/w060s40
git submodule deinit Terrain/w070s40
git submodule deinit Terrain/w080s40
git submodule deinit Terrain/w090s40
git submodule deinit Terrain/w180s40

git submodule update --progress Objects/e010s40
git submodule update --progress Objects/e020s40
git submodule update --progress Objects/e030s40
git submodule update --progress Objects/e070s40
git submodule update --progress Objects/e110s40
git submodule update --progress Objects/e120s40
git submodule update --progress Objects/e130s40
git submodule update --progress Objects/e140s40
git submodule update --progress Objects/e150s40
git submodule update --progress Objects/e170s40
git submodule update --progress Objects/w020s40
git submodule update --progress Objects/w040s40
git submodule update --progress Objects/w060s40
git submodule update --progress Objects/w070s40
git submodule update --progress Objects/w080s40
git submodule update --progress Objects/w090s40
git submodule update --progress Objects/w180s40
git submodule update --progress Terrain/e010s40
git submodule update --progress Terrain/e020s40
git submodule update --progress Terrain/e030s40
git submodule update --progress Terrain/e070s40
git submodule update --progress Terrain/e110s40
git submodule update --progress Terrain/e120s40
git submodule update --progress Terrain/e130s40
git submodule update --progress Terrain/e140s40
git submodule update --progress Terrain/e150s40
git submodule update --progress Terrain/e170s40
git submodule update --progress Terrain/w020s40
git submodule update --progress Terrain/w040s40
git submodule update --progress Terrain/w060s40
git submodule update --progress Terrain/w070s40
git submodule update --progress Terrain/w080s40
git submodule update --progress Terrain/w090s40
git submodule update --progress Terrain/w180s40


