#!/bin/sh

## USAGE EXAMPLE
##
## deinsall/lat-n70
## deinsalls tiles covering lat-n70

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e000n70
git submodule deinit Objects/e010n70
git submodule deinit Objects/e020n70
git submodule deinit Objects/e030n70
git submodule deinit Objects/e040n70
git submodule deinit Objects/e050n70
git submodule deinit Objects/e060n70
git submodule deinit Objects/e070n70
git submodule deinit Objects/e080n70
git submodule deinit Objects/e090n70
git submodule deinit Objects/e100n70
git submodule deinit Objects/e110n70
git submodule deinit Objects/e120n70
git submodule deinit Objects/e130n70
git submodule deinit Objects/e140n70
git submodule deinit Objects/e150n70
git submodule deinit Objects/e160n70
git submodule deinit Objects/e170n70
git submodule deinit Objects/w010n70
git submodule deinit Objects/w020n70
git submodule deinit Objects/w030n70
git submodule deinit Objects/w040n70
git submodule deinit Objects/w050n70
git submodule deinit Objects/w060n70
git submodule deinit Objects/w070n70
git submodule deinit Objects/w080n70
git submodule deinit Objects/w090n70
git submodule deinit Objects/w100n70
git submodule deinit Objects/w110n70
git submodule deinit Objects/w120n70
git submodule deinit Objects/w130n70
git submodule deinit Objects/w140n70
git submodule deinit Objects/w150n70
git submodule deinit Objects/w160n70
git submodule deinit Objects/w170n70
git submodule deinit Objects/w180n70
git submodule deinit Terrain/e000n70
git submodule deinit Terrain/e010n70
git submodule deinit Terrain/e020n70
git submodule deinit Terrain/e030n70
git submodule deinit Terrain/e040n70
git submodule deinit Terrain/e050n70
git submodule deinit Terrain/e060n70
git submodule deinit Terrain/e070n70
git submodule deinit Terrain/e080n70
git submodule deinit Terrain/e090n70
git submodule deinit Terrain/e100n70
git submodule deinit Terrain/e110n70
git submodule deinit Terrain/e120n70
git submodule deinit Terrain/e130n70
git submodule deinit Terrain/e140n70
git submodule deinit Terrain/e150n70
git submodule deinit Terrain/e160n70
git submodule deinit Terrain/e170n70
git submodule deinit Terrain/w010n70
git submodule deinit Terrain/w020n70
git submodule deinit Terrain/w030n70
git submodule deinit Terrain/w040n70
git submodule deinit Terrain/w050n70
git submodule deinit Terrain/w060n70
git submodule deinit Terrain/w070n70
git submodule deinit Terrain/w080n70
git submodule deinit Terrain/w090n70
git submodule deinit Terrain/w100n70
git submodule deinit Terrain/w110n70
git submodule deinit Terrain/w120n70
git submodule deinit Terrain/w130n70
git submodule deinit Terrain/w140n70
git submodule deinit Terrain/w150n70
git submodule deinit Terrain/w160n70
git submodule deinit Terrain/w170n70
git submodule deinit Terrain/w180n70

git submodule update --progress Objects/e000n70
git submodule update --progress Objects/e010n70
git submodule update --progress Objects/e020n70
git submodule update --progress Objects/e030n70
git submodule update --progress Objects/e040n70
git submodule update --progress Objects/e050n70
git submodule update --progress Objects/e060n70
git submodule update --progress Objects/e070n70
git submodule update --progress Objects/e080n70
git submodule update --progress Objects/e090n70
git submodule update --progress Objects/e100n70
git submodule update --progress Objects/e110n70
git submodule update --progress Objects/e120n70
git submodule update --progress Objects/e130n70
git submodule update --progress Objects/e140n70
git submodule update --progress Objects/e150n70
git submodule update --progress Objects/e160n70
git submodule update --progress Objects/e170n70
git submodule update --progress Objects/w010n70
git submodule update --progress Objects/w020n70
git submodule update --progress Objects/w030n70
git submodule update --progress Objects/w040n70
git submodule update --progress Objects/w050n70
git submodule update --progress Objects/w060n70
git submodule update --progress Objects/w070n70
git submodule update --progress Objects/w080n70
git submodule update --progress Objects/w090n70
git submodule update --progress Objects/w100n70
git submodule update --progress Objects/w110n70
git submodule update --progress Objects/w120n70
git submodule update --progress Objects/w130n70
git submodule update --progress Objects/w140n70
git submodule update --progress Objects/w150n70
git submodule update --progress Objects/w160n70
git submodule update --progress Objects/w170n70
git submodule update --progress Objects/w180n70
git submodule update --progress Terrain/e000n70
git submodule update --progress Terrain/e010n70
git submodule update --progress Terrain/e020n70
git submodule update --progress Terrain/e030n70
git submodule update --progress Terrain/e040n70
git submodule update --progress Terrain/e050n70
git submodule update --progress Terrain/e060n70
git submodule update --progress Terrain/e070n70
git submodule update --progress Terrain/e080n70
git submodule update --progress Terrain/e090n70
git submodule update --progress Terrain/e100n70
git submodule update --progress Terrain/e110n70
git submodule update --progress Terrain/e120n70
git submodule update --progress Terrain/e130n70
git submodule update --progress Terrain/e140n70
git submodule update --progress Terrain/e150n70
git submodule update --progress Terrain/e160n70
git submodule update --progress Terrain/e170n70
git submodule update --progress Terrain/w010n70
git submodule update --progress Terrain/w020n70
git submodule update --progress Terrain/w030n70
git submodule update --progress Terrain/w040n70
git submodule update --progress Terrain/w050n70
git submodule update --progress Terrain/w060n70
git submodule update --progress Terrain/w070n70
git submodule update --progress Terrain/w080n70
git submodule update --progress Terrain/w090n70
git submodule update --progress Terrain/w100n70
git submodule update --progress Terrain/w110n70
git submodule update --progress Terrain/w120n70
git submodule update --progress Terrain/w130n70
git submodule update --progress Terrain/w140n70
git submodule update --progress Terrain/w150n70
git submodule update --progress Terrain/w160n70
git submodule update --progress Terrain/w170n70
git submodule update --progress Terrain/w180n70
