#!/bin/sh

## USAGE EXAMPLE
##
## deinsall/lat-s50
## deinsalls tiles covering lat-s50

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e030s50
git submodule deinit Objects/e050s50
git submodule deinit Objects/e060s50
git submodule deinit Objects/e070s50
git submodule deinit Objects/e140s50
git submodule deinit Objects/e160s50
git submodule deinit Objects/e170s50
git submodule deinit Objects/w010s50
git submodule deinit Objects/w020s50
git submodule deinit Objects/w070s50
git submodule deinit Objects/w080s50
git submodule deinit Objects/w180s50
git submodule deinit Terrain/e030s50
git submodule deinit Terrain/e050s50
git submodule deinit Terrain/e060s50
git submodule deinit Terrain/e070s50
git submodule deinit Terrain/e140s50
git submodule deinit Terrain/e160s50
git submodule deinit Terrain/e170s50
git submodule deinit Terrain/w010s50
git submodule deinit Terrain/w020s50
git submodule deinit Terrain/w070s50
git submodule deinit Terrain/w080s50
git submodule deinit Terrain/w180s50

git submodule update --progress Objects/e030s50
git submodule update --progress Objects/e050s50
git submodule update --progress Objects/e060s50
git submodule update --progress Objects/e070s50
git submodule update --progress Objects/e140s50
git submodule update --progress Objects/e160s50
git submodule update --progress Objects/e170s50
git submodule update --progress Objects/w010s50
git submodule update --progress Objects/w020s50
git submodule update --progress Objects/w070s50
git submodule update --progress Objects/w080s50
git submodule update --progress Objects/w180s50
git submodule update --progress Terrain/e030s50
git submodule update --progress Terrain/e050s50
git submodule update --progress Terrain/e060s50
git submodule update --progress Terrain/e070s50
git submodule update --progress Terrain/e140s50
git submodule update --progress Terrain/e160s50
git submodule update --progress Terrain/e170s50
git submodule update --progress Terrain/w010s50
git submodule update --progress Terrain/w020s50
git submodule update --progress Terrain/w070s50
git submodule update --progress Terrain/w080s50
git submodule update --progress Terrain/w180s50
