#!/bin/sh

## USAGE EXAMPLE
##
## deinsall/lat-n30
## deinsalls tiles covering lat-n30

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e000n30
git submodule deinit Objects/e010n30
git submodule deinit Objects/e020n30
git submodule deinit Objects/e030n30
git submodule deinit Objects/e040n30
git submodule deinit Objects/e050n30
git submodule deinit Objects/e060n30
git submodule deinit Objects/e070n30
git submodule deinit Objects/e080n30
git submodule deinit Objects/e090n30
git submodule deinit Objects/e100n30
git submodule deinit Objects/e110n30
git submodule deinit Objects/e120n30
git submodule deinit Objects/e130n30
git submodule deinit Objects/e140n30
git submodule deinit Objects/w010n30
git submodule deinit Objects/w020n30
git submodule deinit Objects/w030n30
git submodule deinit Objects/w040n30
git submodule deinit Objects/w070n30
git submodule deinit Objects/w080n30
git submodule deinit Objects/w090n30
git submodule deinit Objects/w100n30
git submodule deinit Objects/w110n30
git submodule deinit Objects/w120n30
git submodule deinit Objects/w130n30
git submodule deinit Terrain/e000n30
git submodule deinit Terrain/e010n30
git submodule deinit Terrain/e020n30
git submodule deinit Terrain/e030n30
git submodule deinit Terrain/e040n30
git submodule deinit Terrain/e050n30
git submodule deinit Terrain/e060n30
git submodule deinit Terrain/e070n30
git submodule deinit Terrain/e080n30
git submodule deinit Terrain/e090n30
git submodule deinit Terrain/e100n30
git submodule deinit Terrain/e110n30
git submodule deinit Terrain/e120n30
git submodule deinit Terrain/e130n30
git submodule deinit Terrain/e140n30
git submodule deinit Terrain/w010n30
git submodule deinit Terrain/w020n30
git submodule deinit Terrain/w030n30
git submodule deinit Terrain/w040n30
git submodule deinit Terrain/w070n30
git submodule deinit Terrain/w080n30
git submodule deinit Terrain/w090n30
git submodule deinit Terrain/w100n30
git submodule deinit Terrain/w110n30
git submodule deinit Terrain/w120n30
git submodule deinit Terrain/w130n30

git submodule update Objects/e000n30
git submodule update Objects/e010n30
git submodule update Objects/e020n30
git submodule update Objects/e030n30
git submodule update Objects/e040n30
git submodule update Objects/e050n30
git submodule update Objects/e060n30
git submodule update Objects/e070n30
git submodule update Objects/e080n30
git submodule update Objects/e090n30
git submodule update Objects/e100n30
git submodule update Objects/e110n30
git submodule update Objects/e120n30
git submodule update Objects/e130n30
git submodule update Objects/e140n30
git submodule update Objects/w010n30
git submodule update Objects/w020n30
git submodule update Objects/w030n30
git submodule update Objects/w040n30
git submodule update Objects/w070n30
git submodule update Objects/w080n30
git submodule update Objects/w090n30
git submodule update Objects/w100n30
git submodule update Objects/w110n30
git submodule update Objects/w120n30
git submodule update Objects/w130n30
git submodule update Terrain/e000n30
git submodule update Terrain/e010n30
git submodule update Terrain/e020n30
git submodule update Terrain/e030n30
git submodule update Terrain/e040n30
git submodule update Terrain/e050n30
git submodule update Terrain/e060n30
git submodule update Terrain/e070n30
git submodule update Terrain/e080n30
git submodule update Terrain/e090n30
git submodule update Terrain/e100n30
git submodule update Terrain/e110n30
git submodule update Terrain/e120n30
git submodule update Terrain/e130n30
git submodule update Terrain/e140n30
git submodule update Terrain/w010n30
git submodule update Terrain/w020n30
git submodule update Terrain/w030n30
git submodule update Terrain/w040n30
git submodule update Terrain/w070n30
git submodule update Terrain/w080n30
git submodule update Terrain/w090n30
git submodule update Terrain/w100n30
git submodule update Terrain/w110n30
git submodule update Terrain/w120n30
git submodule update Terrain/w130n30
