#!/bin/sh

## USAGE EXAMPLE
##
## deinsall/lat-s60
## deinsalls tiles covering lat-s60

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e000s60
git submodule deinit Objects/e010s60
git submodule deinit Objects/e020s60
git submodule deinit Objects/e030s60
git submodule deinit Objects/e040s60
git submodule deinit Objects/e050s60
git submodule deinit Objects/e060s60
git submodule deinit Objects/e070s60
git submodule deinit Objects/e080s60
git submodule deinit Objects/e090s60
git submodule deinit Objects/e150s60
git submodule deinit Objects/e160s60
git submodule deinit Objects/w010s60
git submodule deinit Objects/w020s60
git submodule deinit Objects/w030s60
git submodule deinit Objects/w040s60
git submodule deinit Objects/w050s60
git submodule deinit Objects/w060s60
git submodule deinit Objects/w070s60
git submodule deinit Objects/w080s60
git submodule deinit Terrain/e000s60
git submodule deinit Terrain/e010s60
git submodule deinit Terrain/e020s60
git submodule deinit Terrain/e030s60
git submodule deinit Terrain/e040s60
git submodule deinit Terrain/e050s60
git submodule deinit Terrain/e060s60
git submodule deinit Terrain/e070s60
git submodule deinit Terrain/e080s60
git submodule deinit Terrain/e090s60
git submodule deinit Terrain/e150s60
git submodule deinit Terrain/e160s60
git submodule deinit Terrain/w010s60
git submodule deinit Terrain/w020s60
git submodule deinit Terrain/w030s60
git submodule deinit Terrain/w040s60
git submodule deinit Terrain/w050s60
git submodule deinit Terrain/w060s60
git submodule deinit Terrain/w070s60
git submodule deinit Terrain/w080s60

git submodule update --progress Objects/e000s60
git submodule update --progress Objects/e010s60
git submodule update --progress Objects/e020s60
git submodule update --progress Objects/e030s60
git submodule update --progress Objects/e040s60
git submodule update --progress Objects/e050s60
git submodule update --progress Objects/e060s60
git submodule update --progress Objects/e070s60
git submodule update --progress Objects/e080s60
git submodule update --progress Objects/e090s60
git submodule update --progress Objects/e150s60
git submodule update --progress Objects/e160s60
git submodule update --progress Objects/w010s60
git submodule update --progress Objects/w020s60
git submodule update --progress Objects/w030s60
git submodule update --progress Objects/w040s60
git submodule update --progress Objects/w050s60
git submodule update --progress Objects/w060s60
git submodule update --progress Objects/w070s60
git submodule update --progress Objects/w080s60
git submodule update --progress Terrain/e000s60
git submodule update --progress Terrain/e010s60
git submodule update --progress Terrain/e020s60
git submodule update --progress Terrain/e030s60
git submodule update --progress Terrain/e040s60
git submodule update --progress Terrain/e050s60
git submodule update --progress Terrain/e060s60
git submodule update --progress Terrain/e070s60
git submodule update --progress Terrain/e080s60
git submodule update --progress Terrain/e090s60
git submodule update --progress Terrain/e150s60
git submodule update --progress Terrain/e160s60
git submodule update --progress Terrain/w010s60
git submodule update --progress Terrain/w020s60
git submodule update --progress Terrain/w030s60
git submodule update --progress Terrain/w040s60
git submodule update --progress Terrain/w050s60
git submodule update --progress Terrain/w060s60
git submodule update --progress Terrain/w070s60
git submodule update --progress Terrain/w080s60
