#!/bin/sh

## USAGE EXAMPLE
##
## deinsall/lat-n10
## deinsalls tiles covering lat-n10

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e000n10
git submodule deinit Objects/e010n10
git submodule deinit Objects/e020n10
git submodule deinit Objects/e030n10
git submodule deinit Objects/e040n10
git submodule deinit Objects/e050n10
git submodule deinit Objects/e070n10
git submodule deinit Objects/e080n10
git submodule deinit Objects/e090n10
git submodule deinit Objects/e100n10
git submodule deinit Objects/e110n10
git submodule deinit Objects/e120n10
git submodule deinit Objects/e130n10
git submodule deinit Objects/e140n10
git submodule deinit Objects/e160n10
git submodule deinit Objects/e170n10
git submodule deinit Objects/w010n10
git submodule deinit Objects/w020n10
git submodule deinit Objects/w030n10
git submodule deinit Objects/w060n10
git submodule deinit Objects/w070n10
git submodule deinit Objects/w080n10
git submodule deinit Objects/w090n10
git submodule deinit Objects/w100n10
git submodule deinit Objects/w110n10
git submodule deinit Objects/w120n10
git submodule deinit Objects/w150n10
git submodule deinit Objects/w160n10
git submodule deinit Objects/w170n10
git submodule deinit Terrain/e000n10
git submodule deinit Terrain/e010n10
git submodule deinit Terrain/e020n10
git submodule deinit Terrain/e030n10
git submodule deinit Terrain/e040n10
git submodule deinit Terrain/e050n10
git submodule deinit Terrain/e070n10
git submodule deinit Terrain/e080n10
git submodule deinit Terrain/e090n10
git submodule deinit Terrain/e100n10
git submodule deinit Terrain/e110n10
git submodule deinit Terrain/e120n10
git submodule deinit Terrain/e130n10
git submodule deinit Terrain/e140n10
git submodule deinit Terrain/e160n10
git submodule deinit Terrain/e170n10
git submodule deinit Terrain/w010n10
git submodule deinit Terrain/w020n10
git submodule deinit Terrain/w030n10
git submodule deinit Terrain/w060n10
git submodule deinit Terrain/w070n10
git submodule deinit Terrain/w080n10
git submodule deinit Terrain/w090n10
git submodule deinit Terrain/w100n10
git submodule deinit Terrain/w110n10
git submodule deinit Terrain/w120n10
git submodule deinit Terrain/w150n10
git submodule deinit Terrain/w160n10
git submodule deinit Terrain/w170n10

git submodule update --progress Objects/e000n10
git submodule update --progress Objects/e010n10
git submodule update --progress Objects/e020n10
git submodule update --progress Objects/e030n10
git submodule update --progress Objects/e040n10
git submodule update --progress Objects/e050n10
git submodule update --progress Objects/e070n10
git submodule update --progress Objects/e080n10
git submodule update --progress Objects/e090n10
git submodule update --progress Objects/e100n10
git submodule update --progress Objects/e110n10
git submodule update --progress Objects/e120n10
git submodule update --progress Objects/e130n10
git submodule update --progress Objects/e140n10
git submodule update --progress Objects/e160n10
git submodule update --progress Objects/e170n10
git submodule update --progress Objects/w010n10
git submodule update --progress Objects/w020n10
git submodule update --progress Objects/w030n10
git submodule update --progress Objects/w060n10
git submodule update --progress Objects/w070n10
git submodule update --progress Objects/w080n10
git submodule update --progress Objects/w090n10
git submodule update --progress Objects/w100n10
git submodule update --progress Objects/w110n10
git submodule update --progress Objects/w120n10
git submodule update --progress Objects/w150n10
git submodule update --progress Objects/w160n10
git submodule update --progress Objects/w170n10
git submodule update --progress Terrain/e000n10
git submodule update --progress Terrain/e010n10
git submodule update --progress Terrain/e020n10
git submodule update --progress Terrain/e030n10
git submodule update --progress Terrain/e040n10
git submodule update --progress Terrain/e050n10
git submodule update --progress Terrain/e070n10
git submodule update --progress Terrain/e080n10
git submodule update --progress Terrain/e090n10
git submodule update --progress Terrain/e100n10
git submodule update --progress Terrain/e110n10
git submodule update --progress Terrain/e120n10
git submodule update --progress Terrain/e130n10
git submodule update --progress Terrain/e140n10
git submodule update --progress Terrain/e160n10
git submodule update --progress Terrain/e170n10
git submodule update --progress Terrain/w010n10
git submodule update --progress Terrain/w020n10
git submodule update --progress Terrain/w030n10
git submodule update --progress Terrain/w060n10
git submodule update --progress Terrain/w070n10
git submodule update --progress Terrain/w080n10
git submodule update --progress Terrain/w090n10
git submodule update --progress Terrain/w100n10
git submodule update --progress Terrain/w110n10
git submodule update --progress Terrain/w120n10
git submodule update --progress Terrain/w150n10
git submodule update --progress Terrain/w160n10
git submodule update --progress Terrain/w170n10
