#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/lat-s90
## deinstalls tiles covering Latitude s90

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (deinitializing and updating both Terrain and Objects)

git submodule deinit Objects/e000s90
git submodule deinit Objects/e010s90
git submodule deinit Objects/e020s90
git submodule deinit Objects/e030s90
git submodule deinit Objects/e040s90
git submodule deinit Objects/e050s90
git submodule deinit Objects/e060s90
git submodule deinit Objects/e070s90
git submodule deinit Objects/e080s90
git submodule deinit Objects/e090s90
git submodule deinit Objects/e100s90
git submodule deinit Objects/e110s90
git submodule deinit Objects/e120s90
git submodule deinit Objects/e130s90
git submodule deinit Objects/e140s90
git submodule deinit Objects/e150s90
git submodule deinit Objects/e160s90
git submodule deinit Objects/e170s90
git submodule deinit Objects/w010s90
git submodule deinit Objects/w020s90
git submodule deinit Objects/w030s90
git submodule deinit Objects/w040s90
git submodule deinit Objects/w050s90
git submodule deinit Objects/w060s90
git submodule deinit Objects/w070s90
git submodule deinit Objects/w080s90
git submodule deinit Objects/w090s90
git submodule deinit Objects/w100s90
git submodule deinit Objects/w110s90
git submodule deinit Objects/w120s90
git submodule deinit Objects/w130s90
git submodule deinit Objects/w140s90
git submodule deinit Objects/w150s90
git submodule deinit Objects/w160s90
git submodule deinit Objects/w170s90
git submodule deinit Objects/w180s90
git submodule deinit Terrain/e000s90
git submodule deinit Terrain/e010s90
git submodule deinit Terrain/e020s90
git submodule deinit Terrain/e030s90
git submodule deinit Terrain/e040s90
git submodule deinit Terrain/e050s90
git submodule deinit Terrain/e060s90
git submodule deinit Terrain/e070s90
git submodule deinit Terrain/e080s90
git submodule deinit Terrain/e090s90
git submodule deinit Terrain/e100s90
git submodule deinit Terrain/e110s90
git submodule deinit Terrain/e120s90
git submodule deinit Terrain/e130s90
git submodule deinit Terrain/e140s90
git submodule deinit Terrain/e150s90
git submodule deinit Terrain/e160s90
git submodule deinit Terrain/e170s90
git submodule deinit Terrain/w010s90
git submodule deinit Terrain/w020s90
git submodule deinit Terrain/w030s90
git submodule deinit Terrain/w040s90
git submodule deinit Terrain/w050s90
git submodule deinit Terrain/w060s90
git submodule deinit Terrain/w070s90
git submodule deinit Terrain/w080s90
git submodule deinit Terrain/w090s90
git submodule deinit Terrain/w100s90
git submodule deinit Terrain/w110s90
git submodule deinit Terrain/w120s90
git submodule deinit Terrain/w130s90
git submodule deinit Terrain/w140s90
git submodule deinit Terrain/w150s90
git submodule deinit Terrain/w160s90
git submodule deinit Terrain/w170s90
git submodule deinit Terrain/w180s90

git submodule update Objects/e000s90
git submodule update Objects/e010s90
git submodule update Objects/e020s90
git submodule update Objects/e030s90
git submodule update Objects/e040s90
git submodule update Objects/e050s90
git submodule update Objects/e060s90
git submodule update Objects/e070s90
git submodule update Objects/e080s90
git submodule update Objects/e090s90
git submodule update Objects/e100s90
git submodule update Objects/e110s90
git submodule update Objects/e120s90
git submodule update Objects/e130s90
git submodule update Objects/e140s90
git submodule update Objects/e150s90
git submodule update Objects/e160s90
git submodule update Objects/e170s90
git submodule update Objects/w010s90
git submodule update Objects/w020s90
git submodule update Objects/w030s90
git submodule update Objects/w040s90
git submodule update Objects/w050s90
git submodule update Objects/w060s90
git submodule update Objects/w070s90
git submodule update Objects/w080s90
git submodule update Objects/w090s90
git submodule update Objects/w100s90
git submodule update Objects/w110s90
git submodule update Objects/w120s90
git submodule update Objects/w130s90
git submodule update Objects/w140s90
git submodule update Objects/w150s90
git submodule update Objects/w160s90
git submodule update Objects/w170s90
git submodule update Objects/w180s90
git submodule update Terrain/e000s90
git submodule update Terrain/e010s90
git submodule update Terrain/e020s90
git submodule update Terrain/e030s90
git submodule update Terrain/e040s90
git submodule update Terrain/e050s90
git submodule update Terrain/e060s90
git submodule update Terrain/e070s90
git submodule update Terrain/e080s90
git submodule update Terrain/e090s90
git submodule update Terrain/e100s90
git submodule update Terrain/e110s90
git submodule update Terrain/e120s90
git submodule update Terrain/e130s90
git submodule update Terrain/e140s90
git submodule update Terrain/e150s90
git submodule update Terrain/e160s90
git submodule update Terrain/e170s90
git submodule update Terrain/w010s90
git submodule update Terrain/w020s90
git submodule update Terrain/w030s90
git submodule update Terrain/w040s90
git submodule update Terrain/w050s90
git submodule update Terrain/w060s90
git submodule update Terrain/w070s90
git submodule update Terrain/w080s90
git submodule update Terrain/w090s90
git submodule update Terrain/w100s90
git submodule update Terrain/w110s90
git submodule update Terrain/w120s90
git submodule update Terrain/w130s90
git submodule update Terrain/w140s90
git submodule update Terrain/w150s90
git submodule update Terrain/w160s90
git submodule update Terrain/w170s90
git submodule update Terrain/w180s90
