#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/lon-w110
## deinstalls tiles covering lon-w110 

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/w110n10
git submodule deinit Objects/w110n20
git submodule deinit Objects/w110n30
git submodule deinit Objects/w110n40
git submodule deinit Objects/w110n50
git submodule deinit Objects/w110n60
git submodule deinit Objects/w110n70
git submodule deinit Objects/w110n80
git submodule deinit Objects/w110s20
git submodule deinit Objects/w110s30
git submodule deinit Objects/w110s70
git submodule deinit Objects/w110s80
git submodule deinit Objects/w110s90
git submodule deinit Terrain/w110n10
git submodule deinit Terrain/w110n20
git submodule deinit Terrain/w110n30
git submodule deinit Terrain/w110n40
git submodule deinit Terrain/w110n50
git submodule deinit Terrain/w110n60
git submodule deinit Terrain/w110n70
git submodule deinit Terrain/w110n80
git submodule deinit Terrain/w110s20
git submodule deinit Terrain/w110s30
git submodule deinit Terrain/w110s70
git submodule deinit Terrain/w110s80
git submodule deinit Terrain/w110s90

git submodule update --progress Objects/w110n10
git submodule update --progress Objects/w110n20
git submodule update --progress Objects/w110n30
git submodule update --progress Objects/w110n40
git submodule update --progress Objects/w110n50
git submodule update --progress Objects/w110n60
git submodule update --progress Objects/w110n70
git submodule update --progress Objects/w110n80
git submodule update --progress Objects/w110s20
git submodule update --progress Objects/w110s30
git submodule update --progress Objects/w110s70
git submodule update --progress Objects/w110s80
git submodule update --progress Objects/w110s90
git submodule update --progress Terrain/w110n10
git submodule update --progress Terrain/w110n20
git submodule update --progress Terrain/w110n30
git submodule update --progress Terrain/w110n40
git submodule update --progress Terrain/w110n50
git submodule update --progress Terrain/w110n60
git submodule update --progress Terrain/w110n70
git submodule update --progress Terrain/w110n80
git submodule update --progress Terrain/w110s20
git submodule update --progress Terrain/w110s30
git submodule update --progress Terrain/w110s70
git submodule update --progress Terrain/w110s80
git submodule update --progress Terrain/w110s90
