#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/lon-w120
## deinstalls tiles covering lon-w120

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/w120n10
git submodule deinit Objects/w120n20
git submodule deinit Objects/w120n30
git submodule deinit Objects/w120n40
git submodule deinit Objects/w120n50
git submodule deinit Objects/w120n60
git submodule deinit Objects/w120n70
git submodule deinit Objects/w120n80
git submodule deinit Objects/w120s20
git submodule deinit Objects/w120s70
git submodule deinit Objects/w120s80
git submodule deinit Objects/w120s90
git submodule deinit Terrain/w120n10
git submodule deinit Terrain/w120n20
git submodule deinit Terrain/w120n30
git submodule deinit Terrain/w120n40
git submodule deinit Terrain/w120n50
git submodule deinit Terrain/w120n60
git submodule deinit Terrain/w120n70
git submodule deinit Terrain/w120n80
git submodule deinit Terrain/w120s20
git submodule deinit Terrain/w120s70
git submodule deinit Terrain/w120s80
git submodule deinit Terrain/w120s90

git submodule update Objects/w120n10
git submodule update Objects/w120n20
git submodule update Objects/w120n30
git submodule update Objects/w120n40
git submodule update Objects/w120n50
git submodule update Objects/w120n60
git submodule update Objects/w120n70
git submodule update Objects/w120n80
git submodule update Objects/w120s20
git submodule update Objects/w120s70
git submodule update Objects/w120s80
git submodule update Objects/w120s90
git submodule update Terrain/w120n10
git submodule update Terrain/w120n20
git submodule update Terrain/w120n30
git submodule update Terrain/w120n40
git submodule update Terrain/w120n50
git submodule update Terrain/w120n60
git submodule update Terrain/w120n70
git submodule update Terrain/w120n80
git submodule update Terrain/w120s20
git submodule update Terrain/w120s70
git submodule update Terrain/w120s80
git submodule update Terrain/w120s90
