#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/lon-e030
## deinstalls tiles covering lon-e030

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e030n00
git submodule deinit Objects/e030n10
git submodule deinit Objects/e030n20
git submodule deinit Objects/e030n30
git submodule deinit Objects/e030n40
git submodule deinit Objects/e030n50
git submodule deinit Objects/e030n60
git submodule deinit Objects/e030n70
git submodule deinit Objects/e030n80
git submodule deinit Objects/e030s10
git submodule deinit Objects/e030s20
git submodule deinit Objects/e030s30
git submodule deinit Objects/e030s40
git submodule deinit Objects/e030s50
git submodule deinit Objects/e030s60
git submodule deinit Objects/e030s70
git submodule deinit Objects/e030s80
git submodule deinit Objects/e030s90
git submodule deinit Terrain/e030n00
git submodule deinit Terrain/e030n10
git submodule deinit Terrain/e030n20
git submodule deinit Terrain/e030n30
git submodule deinit Terrain/e030n40
git submodule deinit Terrain/e030n50
git submodule deinit Terrain/e030n60
git submodule deinit Terrain/e030n70
git submodule deinit Terrain/e030n80
git submodule deinit Terrain/e030s10
git submodule deinit Terrain/e030s20
git submodule deinit Terrain/e030s30
git submodule deinit Terrain/e030s40
git submodule deinit Terrain/e030s50
git submodule deinit Terrain/e030s60
git submodule deinit Terrain/e030s70
git submodule deinit Terrain/e030s80
git submodule deinit Terrain/e030s90

git submodule update --progress Objects/e030n00
git submodule update --progress Objects/e030n10
git submodule update --progress Objects/e030n20
git submodule update --progress Objects/e030n30
git submodule update --progress Objects/e030n40
git submodule update --progress Objects/e030n50
git submodule update --progress Objects/e030n60
git submodule update --progress Objects/e030n70
git submodule update --progress Objects/e030n80
git submodule update --progress Objects/e030s10
git submodule update --progress Objects/e030s20
git submodule update --progress Objects/e030s30
git submodule update --progress Objects/e030s40
git submodule update --progress Objects/e030s50
git submodule update --progress Objects/e030s60
git submodule update --progress Objects/e030s70
git submodule update --progress Objects/e030s80
git submodule update --progress Objects/e030s90
git submodule update --progress Terrain/e030n00
git submodule update --progress Terrain/e030n10
git submodule update --progress Terrain/e030n20
git submodule update --progress Terrain/e030n30
git submodule update --progress Terrain/e030n40
git submodule update --progress Terrain/e030n50
git submodule update --progress Terrain/e030n60
git submodule update --progress Terrain/e030n70
git submodule update --progress Terrain/e030n80
git submodule update --progress Terrain/e030s10
git submodule update --progress Terrain/e030s20
git submodule update --progress Terrain/e030s30
git submodule update --progress Terrain/e030s40
git submodule update --progress Terrain/e030s50
git submodule update --progress Terrain/e030s60
git submodule update --progress Terrain/e030s70
git submodule update --progress Terrain/e030s80
git submodule update --progress Terrain/e030s90
