#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/lon-e050
## deinstalls tiles covering lon-e050

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e050n00
git submodule deinit Objects/e050n10
git submodule deinit Objects/e050n20
git submodule deinit Objects/e050n30
git submodule deinit Objects/e050n40
git submodule deinit Objects/e050n50
git submodule deinit Objects/e050n60
git submodule deinit Objects/e050n70
git submodule deinit Objects/e050n80
git submodule deinit Objects/e050s10
git submodule deinit Objects/e050s20
git submodule deinit Objects/e050s30
git submodule deinit Objects/e050s50
git submodule deinit Objects/e050s60
git submodule deinit Objects/e050s70
git submodule deinit Objects/e050s80
git submodule deinit Objects/e050s90
git submodule deinit Terrain/e050n00
git submodule deinit Terrain/e050n10
git submodule deinit Terrain/e050n20
git submodule deinit Terrain/e050n30
git submodule deinit Terrain/e050n40
git submodule deinit Terrain/e050n50
git submodule deinit Terrain/e050n60
git submodule deinit Terrain/e050n70
git submodule deinit Terrain/e050n80
git submodule deinit Terrain/e050s10
git submodule deinit Terrain/e050s20
git submodule deinit Terrain/e050s30
git submodule deinit Terrain/e050s50
git submodule deinit Terrain/e050s60
git submodule deinit Terrain/e050s70
git submodule deinit Terrain/e050s80
git submodule deinit Terrain/e050s90

git submodule update Objects/e050n00
git submodule update Objects/e050n10
git submodule update Objects/e050n20
git submodule update Objects/e050n30
git submodule update Objects/e050n40
git submodule update Objects/e050n50
git submodule update Objects/e050n60
git submodule update Objects/e050n70
git submodule update Objects/e050n80
git submodule update Objects/e050s10
git submodule update Objects/e050s20
git submodule update Objects/e050s30
git submodule update Objects/e050s50
git submodule update Objects/e050s60
git submodule update Objects/e050s70
git submodule update Objects/e050s80
git submodule update Objects/e050s90
git submodule update Terrain/e050n00
git submodule update Terrain/e050n10
git submodule update Terrain/e050n20
git submodule update Terrain/e050n30
git submodule update Terrain/e050n40
git submodule update Terrain/e050n50
git submodule update Terrain/e050n60
git submodule update Terrain/e050n70
git submodule update Terrain/e050n80
git submodule update Terrain/e050s10
git submodule update Terrain/e050s20
git submodule update Terrain/e050s30
git submodule update Terrain/e050s50
git submodule update Terrain/e050s60
git submodule update Terrain/e050s70
git submodule update Terrain/e050s80
git submodule update Terrain/e050s90
