#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/lon-e010
## deinstalls tiles covering lon-e010

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e010n00
git submodule deinit Objects/e010n10
git submodule deinit Objects/e010n20
git submodule deinit Objects/e010n30
git submodule deinit Objects/e010n40
git submodule deinit Objects/e010n50
git submodule deinit Objects/e010n60
git submodule deinit Objects/e010n70
git submodule deinit Objects/e010n80
git submodule deinit Objects/e010s10
git submodule deinit Objects/e010s20
git submodule deinit Objects/e010s30
git submodule deinit Objects/e010s40
git submodule deinit Objects/e010s60
git submodule deinit Objects/e010s70
git submodule deinit Objects/e010s80
git submodule deinit Objects/e010s90
git submodule deinit Terrain/e010n00
git submodule deinit Terrain/e010n10
git submodule deinit Terrain/e010n20
git submodule deinit Terrain/e010n30
git submodule deinit Terrain/e010n40
git submodule deinit Terrain/e010n50
git submodule deinit Terrain/e010n60
git submodule deinit Terrain/e010n70
git submodule deinit Terrain/e010n80
git submodule deinit Terrain/e010s10
git submodule deinit Terrain/e010s20
git submodule deinit Terrain/e010s30
git submodule deinit Terrain/e010s40
git submodule deinit Terrain/e010s60
git submodule deinit Terrain/e010s70
git submodule deinit Terrain/e010s80
git submodule deinit Terrain/e010s90

git submodule update --progress Objects/e010n00
git submodule update --progress Objects/e010n10
git submodule update --progress Objects/e010n20
git submodule update --progress Objects/e010n30
git submodule update --progress Objects/e010n40
git submodule update --progress Objects/e010n50
git submodule update --progress Objects/e010n60
git submodule update --progress Objects/e010n70
git submodule update --progress Objects/e010n80
git submodule update --progress Objects/e010s10
git submodule update --progress Objects/e010s20
git submodule update --progress Objects/e010s30
git submodule update --progress Objects/e010s40
git submodule update --progress Objects/e010s60
git submodule update --progress Objects/e010s70
git submodule update --progress Objects/e010s80
git submodule update --progress Objects/e010s90
git submodule update --progress Terrain/e010n00
git submodule update --progress Terrain/e010n10
git submodule update --progress Terrain/e010n20
git submodule update --progress Terrain/e010n30
git submodule update --progress Terrain/e010n40
git submodule update --progress Terrain/e010n50
git submodule update --progress Terrain/e010n60
git submodule update --progress Terrain/e010n70
git submodule update --progress Terrain/e010n80
git submodule update --progress Terrain/e010s10
git submodule update --progress Terrain/e010s20
git submodule update --progress Terrain/e010s30
git submodule update --progress Terrain/e010s40
git submodule update --progress Terrain/e010s60
git submodule update --progress Terrain/e010s70
git submodule update --progress Terrain/e010s80
git submodule update --progress Terrain/e010s90
