#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/lon-e150
## deinstalls tiles covering lon-e150

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/e150n00
git submodule deinit Objects/e150n20
git submodule deinit Objects/e150n40
git submodule deinit Objects/e150n50
git submodule deinit Objects/e150n60
git submodule deinit Objects/e150n70
git submodule deinit Objects/e150n80
git submodule deinit Objects/e150s10
git submodule deinit Objects/e150s20
git submodule deinit Objects/e150s30
git submodule deinit Objects/e150s40
git submodule deinit Objects/e150s60
git submodule deinit Objects/e150s70
git submodule deinit Objects/e150s80
git submodule deinit Objects/e150s90
git submodule deinit Terrain/e150n00
git submodule deinit Terrain/e150n20
git submodule deinit Terrain/e150n40
git submodule deinit Terrain/e150n50
git submodule deinit Terrain/e150n60
git submodule deinit Terrain/e150n70
git submodule deinit Terrain/e150n80
git submodule deinit Terrain/e150s10
git submodule deinit Terrain/e150s20
git submodule deinit Terrain/e150s30
git submodule deinit Terrain/e150s40
git submodule deinit Terrain/e150s60
git submodule deinit Terrain/e150s70
git submodule deinit Terrain/e150s80
git submodule deinit Terrain/e150s90

git submodule update Objects/e150n00
git submodule update Objects/e150n20
git submodule update Objects/e150n40
git submodule update Objects/e150n50
git submodule update Objects/e150n60
git submodule update Objects/e150n70
git submodule update Objects/e150n80
git submodule update Objects/e150s10
git submodule update Objects/e150s20
git submodule update Objects/e150s30
git submodule update Objects/e150s40
git submodule update Objects/e150s60
git submodule update Objects/e150s70
git submodule update Objects/e150s80
git submodule update Objects/e150s90
git submodule update Terrain/e150n00
git submodule update Terrain/e150n20
git submodule update Terrain/e150n40
git submodule update Terrain/e150n50
git submodule update Terrain/e150n60
git submodule update Terrain/e150n70
git submodule update Terrain/e150n80
git submodule update Terrain/e150s10
git submodule update Terrain/e150s20
git submodule update Terrain/e150s30
git submodule update Terrain/e150s40
git submodule update Terrain/e150s60
git submodule update Terrain/e150s70
git submodule update Terrain/e150s80
git submodule update Terrain/e150s90
