#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/NorthAmerica
## deinstalls tiles covering NorthAmerica

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (initializing and updating both Terrain and Objects)

git submodule deinit Objects/w050n80
git submodule deinit Objects/w060n40
git submodule deinit Objects/w060n50
git submodule deinit Objects/w060n60
git submodule deinit Objects/w060n80
git submodule deinit Objects/w070n30
git submodule deinit Objects/w070n40
git submodule deinit Objects/w070n50
git submodule deinit Objects/w070n60
git submodule deinit Objects/w070n70
git submodule deinit Objects/w070n80
git submodule deinit Objects/w080n30
git submodule deinit Objects/w080n40
git submodule deinit Objects/w080n50
git submodule deinit Objects/w080n60
git submodule deinit Objects/w080n70
git submodule deinit Objects/w080n80
git submodule deinit Objects/w090n20
git submodule deinit Objects/w090n30
git submodule deinit Objects/w090n40
git submodule deinit Objects/w090n50
git submodule deinit Objects/w090n60
git submodule deinit Objects/w090n70
git submodule deinit Objects/w090n80
git submodule deinit Objects/w100n30
git submodule deinit Objects/w100n40
git submodule deinit Objects/w100n50
git submodule deinit Objects/w100n60
git submodule deinit Objects/w100n70
git submodule deinit Objects/w100n80
git submodule deinit Objects/w110n30
git submodule deinit Objects/w110n40
git submodule deinit Objects/w110n50
git submodule deinit Objects/w110n60
git submodule deinit Objects/w110n70
git submodule deinit Objects/w110n80
git submodule deinit Objects/w120n30
git submodule deinit Objects/w120n40
git submodule deinit Objects/w120n50
git submodule deinit Objects/w120n60
git submodule deinit Objects/w120n70
git submodule deinit Objects/w120n80
git submodule deinit Objects/w130n30
git submodule deinit Objects/w130n40
git submodule deinit Objects/w130n50
git submodule deinit Objects/w130n60
git submodule deinit Objects/w130n70
git submodule deinit Objects/w130n80
git submodule deinit Objects/w140n50
git submodule deinit Objects/w140n60
git submodule deinit Objects/w140n70
git submodule deinit Objects/w150n50
git submodule deinit Objects/w150n60
git submodule deinit Objects/w160n50
git submodule deinit Objects/w160n60
git submodule deinit Objects/w170n50
git submodule deinit Objects/w170n60
git submodule deinit Objects/w180n50
git submodule deinit Objects/w180n60
git submodule deinit Terrain/w050n80
git submodule deinit Terrain/w060n40
git submodule deinit Terrain/w060n50
git submodule deinit Terrain/w060n60
git submodule deinit Terrain/w060n80
git submodule deinit Terrain/w070n30
git submodule deinit Terrain/w070n40
git submodule deinit Terrain/w070n50
git submodule deinit Terrain/w070n60
git submodule deinit Terrain/w070n70
git submodule deinit Terrain/w070n80
git submodule deinit Terrain/w080n30
git submodule deinit Terrain/w080n40
git submodule deinit Terrain/w080n50
git submodule deinit Terrain/w080n60
git submodule deinit Terrain/w080n70
git submodule deinit Terrain/w080n80
git submodule deinit Terrain/w090n20
git submodule deinit Terrain/w090n30
git submodule deinit Terrain/w090n40
git submodule deinit Terrain/w090n50
git submodule deinit Terrain/w090n60
git submodule deinit Terrain/w090n70
git submodule deinit Terrain/w090n80
git submodule deinit Terrain/w100n30
git submodule deinit Terrain/w100n40
git submodule deinit Terrain/w100n50
git submodule deinit Terrain/w100n60
git submodule deinit Terrain/w100n70
git submodule deinit Terrain/w100n80
git submodule deinit Terrain/w110n30
git submodule deinit Terrain/w110n40
git submodule deinit Terrain/w110n50
git submodule deinit Terrain/w110n60
git submodule deinit Terrain/w110n70
git submodule deinit Terrain/w110n80
git submodule deinit Terrain/w120n30
git submodule deinit Terrain/w120n40
git submodule deinit Terrain/w120n50
git submodule deinit Terrain/w120n60
git submodule deinit Terrain/w120n70
git submodule deinit Terrain/w120n80
git submodule deinit Terrain/w130n30
git submodule deinit Terrain/w130n40
git submodule deinit Terrain/w130n50
git submodule deinit Terrain/w130n60
git submodule deinit Terrain/w130n70
git submodule deinit Terrain/w130n80
git submodule deinit Terrain/w140n50
git submodule deinit Terrain/w140n60
git submodule deinit Terrain/w140n70
git submodule deinit Terrain/w150n50
git submodule deinit Terrain/w150n60
git submodule deinit Terrain/w160n50
git submodule deinit Terrain/w160n60
git submodule deinit Terrain/w170n50
git submodule deinit Terrain/w170n60
git submodule deinit Terrain/w180n50
git submodule deinit Terrain/w180n60
 
git submodule update Objects/w050n80
git submodule update Objects/w060n40
git submodule update Objects/w060n50
git submodule update Objects/w060n60
git submodule update Objects/w060n80
git submodule update Objects/w070n30
git submodule update Objects/w070n40
git submodule update Objects/w070n50
git submodule update Objects/w070n60
git submodule update Objects/w070n70
git submodule update Objects/w070n80
git submodule update Objects/w080n30
git submodule update Objects/w080n40
git submodule update Objects/w080n50
git submodule update Objects/w080n60
git submodule update Objects/w080n70
git submodule update Objects/w080n80
git submodule update Objects/w090n20
git submodule update Objects/w090n30
git submodule update Objects/w090n40
git submodule update Objects/w090n50
git submodule update Objects/w090n60
git submodule update Objects/w090n70
git submodule update Objects/w090n80
git submodule update Objects/w100n30
git submodule update Objects/w100n40
git submodule update Objects/w100n50
git submodule update Objects/w100n60
git submodule update Objects/w100n70
git submodule update Objects/w100n80
git submodule update Objects/w110n30
git submodule update Objects/w110n40
git submodule update Objects/w110n50
git submodule update Objects/w110n60
git submodule update Objects/w110n70
git submodule update Objects/w110n80
git submodule update Objects/w120n30
git submodule update Objects/w120n40
git submodule update Objects/w120n50
git submodule update Objects/w120n60
git submodule update Objects/w120n70
git submodule update Objects/w120n80
git submodule update Objects/w130n30
git submodule update Objects/w130n40
git submodule update Objects/w130n50
git submodule update Objects/w130n60
git submodule update Objects/w130n70
git submodule update Objects/w130n80
git submodule update Objects/w140n50
git submodule update Objects/w140n60
git submodule update Objects/w140n70
git submodule update Objects/w150n50
git submodule update Objects/w150n60
git submodule update Objects/w160n50
git submodule update Objects/w160n60
git submodule update Objects/w170n50
git submodule update Objects/w170n60
git submodule update Objects/w180n50
git submodule update Objects/w180n60
git submodule update Terrain/w050n80
git submodule update Terrain/w060n40
git submodule update Terrain/w060n50
git submodule update Terrain/w060n60
git submodule update Terrain/w060n80
git submodule update Terrain/w070n30
git submodule update Terrain/w070n40
git submodule update Terrain/w070n50
git submodule update Terrain/w070n60
git submodule update Terrain/w070n70
git submodule update Terrain/w070n80
git submodule update Terrain/w080n30
git submodule update Terrain/w080n40
git submodule update Terrain/w080n50
git submodule update Terrain/w080n60
git submodule update Terrain/w080n70
git submodule update Terrain/w080n80
git submodule update Terrain/w090n20
git submodule update Terrain/w090n30
git submodule update Terrain/w090n40
git submodule update Terrain/w090n50
git submodule update Terrain/w090n60
git submodule update Terrain/w090n70
git submodule update Terrain/w090n80
git submodule update Terrain/w100n30
git submodule update Terrain/w100n40
git submodule update Terrain/w100n50
git submodule update Terrain/w100n60
git submodule update Terrain/w100n70
git submodule update Terrain/w100n80
git submodule update Terrain/w110n30
git submodule update Terrain/w110n40
git submodule update Terrain/w110n50
git submodule update Terrain/w110n60
git submodule update Terrain/w110n70
git submodule update Terrain/w110n80
git submodule update Terrain/w120n30
git submodule update Terrain/w120n40
git submodule update Terrain/w120n50
git submodule update Terrain/w120n60
git submodule update Terrain/w120n70
git submodule update Terrain/w120n80
git submodule update Terrain/w130n30
git submodule update Terrain/w130n40
git submodule update Terrain/w130n50
git submodule update Terrain/w130n60
git submodule update Terrain/w130n70
git submodule update Terrain/w130n80
git submodule update Terrain/w140n50
git submodule update Terrain/w140n60
git submodule update Terrain/w140n70
git submodule update Terrain/w150n50
git submodule update Terrain/w150n60
git submodule update Terrain/w160n50
git submodule update Terrain/w160n60
git submodule update Terrain/w170n50
git submodule update Terrain/w170n60
git submodule update Terrain/w180n50
git submodule update Terrain/w180n60
