#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/SouthWestQuadsphere
## deinstalls tiles covering the Southern West Quadsphere

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (deinitializing and updating both Terrain and Objects)

git submodule deinit Objects/w010s70
git submodule deinit Objects/w020s70
git submodule deinit Objects/w030s70
git submodule deinit Objects/w040s70
git submodule deinit Objects/w050s70
git submodule deinit Objects/w060s70
git submodule deinit Objects/w070s70
git submodule deinit Objects/w080s70
git submodule deinit Objects/w090s70
git submodule deinit Objects/w100s70
git submodule deinit Objects/w110s70
git submodule deinit Objects/w120s70
git submodule deinit Objects/w130s70
git submodule deinit Objects/w140s70
git submodule deinit Objects/w150s70
git submodule deinit Objects/w160s70
git submodule deinit Objects/w170s70
git submodule deinit Objects/w180s70
git submodule deinit Terrain/w010s80
git submodule deinit Terrain/w020s80
git submodule deinit Terrain/w030s80
git submodule deinit Terrain/w040s80
git submodule deinit Terrain/w050s80
git submodule deinit Terrain/w060s80
git submodule deinit Terrain/w070s80
git submodule deinit Terrain/w080s80
git submodule deinit Terrain/w090s80
git submodule deinit Terrain/w100s80
git submodule deinit Terrain/w110s80
git submodule deinit Terrain/w120s80
git submodule deinit Terrain/w130s80
git submodule deinit Terrain/w140s80
git submodule deinit Terrain/w150s80
git submodule deinit Terrain/w160s80
git submodule deinit Terrain/w170s80
git submodule deinit Terrain/w180s80
git submodule deinit Terrain/w010s90
git submodule deinit Terrain/w020s90
git submodule deinit Terrain/w030s90
git submodule deinit Terrain/w040s90
git submodule deinit Terrain/w050s90
git submodule deinit Terrain/w060s90
git submodule deinit Terrain/w070s90
git submodule deinit Terrain/w080s90
git submodule deinit Terrain/w090s90
git submodule deinit Terrain/w100s90
git submodule deinit Terrain/w110s90
git submodule deinit Terrain/w120s90
git submodule deinit Terrain/w130s90
git submodule deinit Terrain/w140s90
git submodule deinit Terrain/w150s90
git submodule deinit Terrain/w160s90
git submodule deinit Terrain/w170s90
git submodule deinit Terrain/w180s90
git submodule deinit Terrain/w010s70
git submodule deinit Terrain/w020s70
git submodule deinit Terrain/w030s70
git submodule deinit Terrain/w040s70
git submodule deinit Terrain/w050s70
git submodule deinit Terrain/w060s70
git submodule deinit Terrain/w070s70
git submodule deinit Terrain/w080s70
git submodule deinit Terrain/w090s70
git submodule deinit Terrain/w100s70
git submodule deinit Terrain/w110s70
git submodule deinit Terrain/w120s70
git submodule deinit Terrain/w130s70
git submodule deinit Terrain/w140s70
git submodule deinit Terrain/w150s70
git submodule deinit Terrain/w160s70
git submodule deinit Terrain/w170s70
git submodule deinit Terrain/w180s70
git submodule deinit Terrain/w010s80
git submodule deinit Terrain/w020s80
git submodule deinit Terrain/w030s80
git submodule deinit Terrain/w040s80
git submodule deinit Terrain/w050s80
git submodule deinit Terrain/w060s80
git submodule deinit Terrain/w070s80
git submodule deinit Terrain/w080s80
git submodule deinit Terrain/w090s80
git submodule deinit Terrain/w100s80
git submodule deinit Terrain/w110s80
git submodule deinit Terrain/w120s80
git submodule deinit Terrain/w130s80
git submodule deinit Terrain/w140s80
git submodule deinit Terrain/w150s80
git submodule deinit Terrain/w160s80
git submodule deinit Terrain/w170s80
git submodule deinit Terrain/w180s80
git submodule deinit Terrain/w010s90
git submodule deinit Terrain/w020s90
git submodule deinit Terrain/w030s90
git submodule deinit Terrain/w040s90
git submodule deinit Terrain/w050s90
git submodule deinit Terrain/w060s90
git submodule deinit Terrain/w070s90
git submodule deinit Terrain/w080s90
git submodule deinit Terrain/w090s90
git submodule deinit Terrain/w100s90
git submodule deinit Terrain/w110s90
git submodule deinit Terrain/w120s90
git submodule deinit Terrain/w130s90
git submodule deinit Terrain/w140s90
git submodule deinit Terrain/w150s90
git submodule deinit Terrain/w160s90
git submodule deinit Terrain/w170s90
git submodule deinit Terrain/w180s90

git submodule update
