#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/SouthEastQuadsphere
## deinstalls tiles covering the Southern-Eastern Quadsphere

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (deinitializing and updating both Terrain and Objects)

git submodule deinit Objects/e000s70
git submodule deinit Objects/e010s70
git submodule deinit Objects/e020s70
git submodule deinit Objects/e030s70
git submodule deinit Objects/e040s70
git submodule deinit Objects/e050s70
git submodule deinit Objects/e060s70
git submodule deinit Objects/e070s70
git submodule deinit Objects/e080s70
git submodule deinit Objects/e090s70
git submodule deinit Objects/e100s70
git submodule deinit Objects/e110s70
git submodule deinit Objects/e120s70
git submodule deinit Objects/e130s70
git submodule deinit Objects/e140s70
git submodule deinit Objects/e150s70
git submodule deinit Objects/e160s70
git submodule deinit Objects/e170s70
git submodule deinit Terrain/e000s80
git submodule deinit Terrain/e010s80
git submodule deinit Terrain/e020s80
git submodule deinit Terrain/e030s80
git submodule deinit Terrain/e040s80
git submodule deinit Terrain/e050s80
git submodule deinit Terrain/e060s80
git submodule deinit Terrain/e070s80
git submodule deinit Terrain/e080s80
git submodule deinit Terrain/e090s80
git submodule deinit Terrain/e100s80
git submodule deinit Terrain/e110s80
git submodule deinit Terrain/e120s80
git submodule deinit Terrain/e130s80
git submodule deinit Terrain/e140s80
git submodule deinit Terrain/e150s80
git submodule deinit Terrain/e160s80
git submodule deinit Terrain/e170s80
git submodule deinit Terrain/e000s90
git submodule deinit Terrain/e010s90
git submodule deinit Terrain/e020s90
git submodule deinit Terrain/e030s90
git submodule deinit Terrain/e040s90
git submodule deinit Terrain/e050s90
git submodule deinit Terrain/e060s90
git submodule deinit Terrain/e070s90
git submodule deinit Terrain/e080s90
git submodule deinit Terrain/e090s90
git submodule deinit Terrain/e100s90
git submodule deinit Terrain/e110s90
git submodule deinit Terrain/e120s90
git submodule deinit Terrain/e130s90
git submodule deinit Terrain/e140s90
git submodule deinit Terrain/e150s90
git submodule deinit Terrain/e160s90
git submodule deinit Terrain/e170s90
git submodule deinit Terrain/e000s70
git submodule deinit Terrain/e010s70
git submodule deinit Terrain/e020s70
git submodule deinit Terrain/e030s70
git submodule deinit Terrain/e040s70
git submodule deinit Terrain/e050s70
git submodule deinit Terrain/e060s70
git submodule deinit Terrain/e070s70
git submodule deinit Terrain/e080s70
git submodule deinit Terrain/e090s70
git submodule deinit Terrain/e100s70
git submodule deinit Terrain/e110s70
git submodule deinit Terrain/e120s70
git submodule deinit Terrain/e130s70
git submodule deinit Terrain/e140s70
git submodule deinit Terrain/e150s70
git submodule deinit Terrain/e160s70
git submodule deinit Terrain/e170s70
git submodule deinit Terrain/e000s80
git submodule deinit Terrain/e010s80
git submodule deinit Terrain/e020s80
git submodule deinit Terrain/e030s80
git submodule deinit Terrain/e040s80
git submodule deinit Terrain/e050s80
git submodule deinit Terrain/e060s80
git submodule deinit Terrain/e070s80
git submodule deinit Terrain/e080s80
git submodule deinit Terrain/e090s80
git submodule deinit Terrain/e100s80
git submodule deinit Terrain/e110s80
git submodule deinit Terrain/e120s80
git submodule deinit Terrain/e130s80
git submodule deinit Terrain/e140s80
git submodule deinit Terrain/e150s80
git submodule deinit Terrain/e160s80
git submodule deinit Terrain/e170s80
git submodule deinit Terrain/e000s90
git submodule deinit Terrain/e010s90
git submodule deinit Terrain/e020s90
git submodule deinit Terrain/e030s90
git submodule deinit Terrain/e040s90
git submodule deinit Terrain/e050s90
git submodule deinit Terrain/e060s90
git submodule deinit Terrain/e070s90
git submodule deinit Terrain/e080s90
git submodule deinit Terrain/e090s90
git submodule deinit Terrain/e100s90
git submodule deinit Terrain/e110s90
git submodule deinit Terrain/e120s90
git submodule deinit Terrain/e130s90
git submodule deinit Terrain/e140s90
git submodule deinit Terrain/e150s90
git submodule deinit Terrain/e160s90
git submodule deinit Terrain/e170s90

git submodule update
