#!/bin/sh

## USAGE EXAMPLE
##
## deinstall/UK
## deinstalls tiles covering UK

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Deinstall any tile listed completely (deinitializing and updating both Terrain and Objects)

git submodule deinit Objects/e000n50
git submodule deinit Objects/w010n40
git submodule deinit Objects/w010n50
git submodule deinit Objects/w010n60
git submodule deinit Objects/w020n50
git submodule deinit Terrain/e000n50
git submodule deinit Terrain/w010n40
git submodule deinit Terrain/w010n50
git submodule deinit Terrain/w010n60
git submodule deinit Terrain/w020n50

git submodule update --progress Objects/e000n50
git submodule update --progress Objects/w010n40
git submodule update --progress Objects/w010n50
git submodule update --progress Objects/w010n60
git submodule update --progress Objects/w020n50
git submodule update --progress Terrain/e000n50
git submodule update --progress Terrain/w010n40
git submodule update --progress Terrain/w010n50
git submodule update --progress Terrain/w010n60
git submodule update --progress Terrain/w020n50
