#!/bin/sh

## USAGE EXAMPLE
##
## install/Africa
## installs tiles covering Africa

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e000n00
git submodule update --progress --init Objects/e000n00
git submodule update --progress --init Objects/e000n10
git submodule update --progress --init Objects/e000n10
git submodule update --progress --init Objects/e000n20
git submodule update --progress --init Objects/e000n20
git submodule update --progress --init Objects/e000n30
git submodule update --progress --init Objects/e000n30
git submodule update --progress --init Objects/e000s10
git submodule update --progress --init Objects/e000s10
git submodule update --progress --init Objects/e000s20
git submodule update --progress --init Objects/e000s20
git submodule update --progress --init Objects/e010n00
git submodule update --progress --init Objects/e010n10
git submodule update --progress --init Objects/e010n20
git submodule update --progress --init Objects/e010n30
git submodule update --progress --init Objects/e010s10
git submodule update --progress --init Objects/e010s20
git submodule update --progress --init Objects/e010s30
git submodule update --progress --init Objects/e010s40
git submodule update --progress --init Objects/e020n00
git submodule update --progress --init Objects/e020n10
git submodule update --progress --init Objects/e020n20
git submodule update --progress --init Objects/e020n30
git submodule update --progress --init Objects/e020s10
git submodule update --progress --init Objects/e020s20
git submodule update --progress --init Objects/e020s30
git submodule update --progress --init Objects/e020s40
git submodule update --progress --init Objects/e030n00
git submodule update --progress --init Objects/e030n10
git submodule update --progress --init Objects/e030n20
git submodule update --progress --init Objects/e030n30
git submodule update --progress --init Objects/e030s10
git submodule update --progress --init Objects/e030s20
git submodule update --progress --init Objects/e030s30
git submodule update --progress --init Objects/e030s40
git submodule update --progress --init Objects/e040n00
git submodule update --progress --init Objects/e040n10
git submodule update --progress --init Objects/e040s10
git submodule update --progress --init Objects/e040s20
git submodule update --progress --init Objects/e040s30
git submodule update --progress --init Objects/e050n00
git submodule update --progress --init Objects/e050n10
git submodule update --progress --init Objects/e050s10
git submodule update --progress --init Objects/e050s20
git submodule update --progress --init Objects/e050s30
git submodule update --progress --init Objects/w010n00
git submodule update --progress --init Objects/w010n10
git submodule update --progress --init Objects/w010n20
git submodule update --progress --init Objects/w010n30
git submodule update --progress --init Objects/w010s20
git submodule update --progress --init Objects/w020n00
git submodule update --progress --init Objects/w020n10
git submodule update --progress --init Objects/w020n20
git submodule update --progress --init Objects/w020n30
git submodule update --progress --init Objects/w020s10
git submodule update --progress --init Objects/w030n00
git submodule update --progress --init Objects/w030n10
git submodule update --progress --init Objects/w030n30
git submodule update --progress --init Objects/w040n30
git submodule update --progress --init Terrain/e000n00
git submodule update --progress --init Terrain/e000n00
git submodule update --progress --init Terrain/e000n10
git submodule update --progress --init Terrain/e000n10
git submodule update --progress --init Terrain/e000n20
git submodule update --progress --init Terrain/e000n20
git submodule update --progress --init Terrain/e000n30
git submodule update --progress --init Terrain/e000n30
git submodule update --progress --init Terrain/e000s10
git submodule update --progress --init Terrain/e000s10
git submodule update --progress --init Terrain/e000s20
git submodule update --progress --init Terrain/e000s20
git submodule update --progress --init Terrain/e010n00
git submodule update --progress --init Terrain/e010n10
git submodule update --progress --init Terrain/e010n20
git submodule update --progress --init Terrain/e010n30
git submodule update --progress --init Terrain/e010s10
git submodule update --progress --init Terrain/e010s20
git submodule update --progress --init Terrain/e010s30
git submodule update --progress --init Terrain/e010s40
git submodule update --progress --init Terrain/e020n00
git submodule update --progress --init Terrain/e020n10
git submodule update --progress --init Terrain/e020n20
git submodule update --progress --init Terrain/e020n30
git submodule update --progress --init Terrain/e020s10
git submodule update --progress --init Terrain/e020s20
git submodule update --progress --init Terrain/e020s30
git submodule update --progress --init Terrain/e020s40
git submodule update --progress --init Terrain/e030n00
git submodule update --progress --init Terrain/e030n10
git submodule update --progress --init Terrain/e030n20
git submodule update --progress --init Terrain/e030n30
git submodule update --progress --init Terrain/e030s10
git submodule update --progress --init Terrain/e030s20
git submodule update --progress --init Terrain/e030s30
git submodule update --progress --init Terrain/e030s40
git submodule update --progress --init Terrain/e040n00
git submodule update --progress --init Terrain/e040n10
git submodule update --progress --init Terrain/e040s10
git submodule update --progress --init Terrain/e040s20
git submodule update --progress --init Terrain/e040s30
git submodule update --progress --init Terrain/e050n00
git submodule update --progress --init Terrain/e050n10
git submodule update --progress --init Terrain/e050s10
git submodule update --progress --init Terrain/e050s20
git submodule update --progress --init Terrain/e050s30
git submodule update --progress --init Terrain/w010n00
git submodule update --progress --init Terrain/w010n10
git submodule update --progress --init Terrain/w010n20
git submodule update --progress --init Terrain/w010n30
git submodule update --progress --init Terrain/w010s20
git submodule update --progress --init Terrain/w020n00
git submodule update --progress --init Terrain/w020n10
git submodule update --progress --init Terrain/w020n20
git submodule update --progress --init Terrain/w020n30
git submodule update --progress --init Terrain/w020s10
git submodule update --progress --init Terrain/w030n00
git submodule update --progress --init Terrain/w030n10
git submodule update --progress --init Terrain/w030n30
git submodule update --progress --init Terrain/w040n30

