#!/bin/sh

## USAGE EXAMPLE
##
## install/Antartic
## installs tiles covering Antartic

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/e000s70
git submodule init Objects/e010s70
git submodule init Objects/e020s70
git submodule init Objects/e030s70
git submodule init Objects/e040s70
git submodule init Objects/e050s70
git submodule init Objects/e060s70
git submodule init Objects/e070s70
git submodule init Objects/e080s70
git submodule init Objects/e090s70
git submodule init Objects/e100s70
git submodule init Objects/e110s70
git submodule init Objects/e120s70
git submodule init Objects/e130s70
git submodule init Objects/e140s70
git submodule init Objects/e150s70
git submodule init Objects/e160s70
git submodule init Objects/e170s70
git submodule init Objects/w010s70
git submodule init Objects/w020s70
git submodule init Objects/w030s70
git submodule init Objects/w040s70
git submodule init Objects/w050s70
git submodule init Objects/w060s70
git submodule init Objects/w070s70
git submodule init Objects/w080s70
git submodule init Objects/w090s70
git submodule init Objects/w100s70
git submodule init Objects/w110s70
git submodule init Objects/w120s70
git submodule init Objects/w130s70
git submodule init Objects/w140s70
git submodule init Objects/w150s70
git submodule init Objects/w160s70
git submodule init Objects/w170s70
git submodule init Objects/w180s70
git submodule init Terrain/e000s80
git submodule init Terrain/e010s80
git submodule init Terrain/e020s80
git submodule init Terrain/e030s80
git submodule init Terrain/e040s80
git submodule init Terrain/e050s80
git submodule init Terrain/e060s80
git submodule init Terrain/e070s80
git submodule init Terrain/e080s80
git submodule init Terrain/e090s80
git submodule init Terrain/e100s80
git submodule init Terrain/e110s80
git submodule init Terrain/e120s80
git submodule init Terrain/e130s80
git submodule init Terrain/e140s80
git submodule init Terrain/e150s80
git submodule init Terrain/e160s80
git submodule init Terrain/e170s80
git submodule init Terrain/w010s80
git submodule init Terrain/w020s80
git submodule init Terrain/w030s80
git submodule init Terrain/w040s80
git submodule init Terrain/w050s80
git submodule init Terrain/w060s80
git submodule init Terrain/w070s80
git submodule init Terrain/w080s80
git submodule init Terrain/w090s80
git submodule init Terrain/w100s80
git submodule init Terrain/w110s80
git submodule init Terrain/w120s80
git submodule init Terrain/w130s80
git submodule init Terrain/w140s80
git submodule init Terrain/w150s80
git submodule init Terrain/w160s80
git submodule init Terrain/w170s80
git submodule init Terrain/w180s80
git submodule init Terrain/e000s90
git submodule init Terrain/e010s90
git submodule init Terrain/e020s90
git submodule init Terrain/e030s90
git submodule init Terrain/e040s90
git submodule init Terrain/e050s90
git submodule init Terrain/e060s90
git submodule init Terrain/e070s90
git submodule init Terrain/e080s90
git submodule init Terrain/e090s90
git submodule init Terrain/e100s90
git submodule init Terrain/e110s90
git submodule init Terrain/e120s90
git submodule init Terrain/e130s90
git submodule init Terrain/e140s90
git submodule init Terrain/e150s90
git submodule init Terrain/e160s90
git submodule init Terrain/e170s90
git submodule init Terrain/w010s90
git submodule init Terrain/w020s90
git submodule init Terrain/w030s90
git submodule init Terrain/w040s90
git submodule init Terrain/w050s90
git submodule init Terrain/w060s90
git submodule init Terrain/w070s90
git submodule init Terrain/w080s90
git submodule init Terrain/w090s90
git submodule init Terrain/w100s90
git submodule init Terrain/w110s90
git submodule init Terrain/w120s90
git submodule init Terrain/w130s90
git submodule init Terrain/w140s90
git submodule init Terrain/w150s90
git submodule init Terrain/w160s90
git submodule init Terrain/w170s90
git submodule init Terrain/w180s90
git submodule init Terrain/e000s70
git submodule init Terrain/e010s70
git submodule init Terrain/e020s70
git submodule init Terrain/e030s70
git submodule init Terrain/e040s70
git submodule init Terrain/e050s70
git submodule init Terrain/e060s70
git submodule init Terrain/e070s70
git submodule init Terrain/e080s70
git submodule init Terrain/e090s70
git submodule init Terrain/e100s70
git submodule init Terrain/e110s70
git submodule init Terrain/e120s70
git submodule init Terrain/e130s70
git submodule init Terrain/e140s70
git submodule init Terrain/e150s70
git submodule init Terrain/e160s70
git submodule init Terrain/e170s70
git submodule init Terrain/w010s70
git submodule init Terrain/w020s70
git submodule init Terrain/w030s70
git submodule init Terrain/w040s70
git submodule init Terrain/w050s70
git submodule init Terrain/w060s70
git submodule init Terrain/w070s70
git submodule init Terrain/w080s70
git submodule init Terrain/w090s70
git submodule init Terrain/w100s70
git submodule init Terrain/w110s70
git submodule init Terrain/w120s70
git submodule init Terrain/w130s70
git submodule init Terrain/w140s70
git submodule init Terrain/w150s70
git submodule init Terrain/w160s70
git submodule init Terrain/w170s70
git submodule init Terrain/w180s70
git submodule init Terrain/e000s80
git submodule init Terrain/e010s80
git submodule init Terrain/e020s80
git submodule init Terrain/e030s80
git submodule init Terrain/e040s80
git submodule init Terrain/e050s80
git submodule init Terrain/e060s80
git submodule init Terrain/e070s80
git submodule init Terrain/e080s80
git submodule init Terrain/e090s80
git submodule init Terrain/e100s80
git submodule init Terrain/e110s80
git submodule init Terrain/e120s80
git submodule init Terrain/e130s80
git submodule init Terrain/e140s80
git submodule init Terrain/e150s80
git submodule init Terrain/e160s80
git submodule init Terrain/e170s80
git submodule init Terrain/w010s80
git submodule init Terrain/w020s80
git submodule init Terrain/w030s80
git submodule init Terrain/w040s80
git submodule init Terrain/w050s80
git submodule init Terrain/w060s80
git submodule init Terrain/w070s80
git submodule init Terrain/w080s80
git submodule init Terrain/w090s80
git submodule init Terrain/w100s80
git submodule init Terrain/w110s80
git submodule init Terrain/w120s80
git submodule init Terrain/w130s80
git submodule init Terrain/w140s80
git submodule init Terrain/w150s80
git submodule init Terrain/w160s80
git submodule init Terrain/w170s80
git submodule init Terrain/w180s80
git submodule init Terrain/e000s90
git submodule init Terrain/e010s90
git submodule init Terrain/e020s90
git submodule init Terrain/e030s90
git submodule init Terrain/e040s90
git submodule init Terrain/e050s90
git submodule init Terrain/e060s90
git submodule init Terrain/e070s90
git submodule init Terrain/e080s90
git submodule init Terrain/e090s90
git submodule init Terrain/e100s90
git submodule init Terrain/e110s90
git submodule init Terrain/e120s90
git submodule init Terrain/e130s90
git submodule init Terrain/e140s90
git submodule init Terrain/e150s90
git submodule init Terrain/e160s90
git submodule init Terrain/e170s90
git submodule init Terrain/w010s90
git submodule init Terrain/w020s90
git submodule init Terrain/w030s90
git submodule init Terrain/w040s90
git submodule init Terrain/w050s90
git submodule init Terrain/w060s90
git submodule init Terrain/w070s90
git submodule init Terrain/w080s90
git submodule init Terrain/w090s90
git submodule init Terrain/w100s90
git submodule init Terrain/w110s90
git submodule init Terrain/w120s90
git submodule init Terrain/w130s90
git submodule init Terrain/w140s90
git submodule init Terrain/w150s90
git submodule init Terrain/w160s90
git submodule init Terrain/w170s90
git submodule init Terrain/w180s90

git submodule update
