#!/bin/sh

## USAGE EXAMPLE
##
## install/CentralAmerica
## installs tiles covering CentralAmerica

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/w060n10
git submodule update --progress --init Objects/w070n10
git submodule update --progress --init Objects/w080n10
git submodule update --progress --init Objects/w080n20
git submodule update --progress --init Objects/w090n10
git submodule update --progress --init Objects/w090n20
git submodule update --progress --init Objects/w100n10
git submodule update --progress --init Objects/w100n20
git submodule update --progress --init Objects/w110n10
git submodule update --progress --init Objects/w110n20
git submodule update --progress --init Objects/w120n10
git submodule update --progress --init Objects/w120n20
git submodule update --progress --init Objects/w150n10
git submodule update --progress --init Objects/w160n10
git submodule update --progress --init Objects/w160n20
git submodule update --progress --init Objects/w170n10
git submodule update --progress --init Objects/w170n20
git submodule update --progress --init Objects/w180n20
git submodule update --progress --init Terrain/w060n10
git submodule update --progress --init Terrain/w070n10
git submodule update --progress --init Terrain/w080n10
git submodule update --progress --init Terrain/w080n20
git submodule update --progress --init Terrain/w090n10
git submodule update --progress --init Terrain/w090n20
git submodule update --progress --init Terrain/w100n10
git submodule update --progress --init Terrain/w100n20
git submodule update --progress --init Terrain/w110n10
git submodule update --progress --init Terrain/w110n20
git submodule update --progress --init Terrain/w120n10
git submodule update --progress --init Terrain/w120n20
git submodule update --progress --init Terrain/w150n10
git submodule update --progress --init Terrain/w160n10
git submodule update --progress --init Terrain/w160n20
git submodule update --progress --init Terrain/w170n10
git submodule update --progress --init Terrain/w170n20
git submodule update --progress --init Terrain/w180n20
 
