#!/bin/sh

## USAGE EXAMPLE
##
## install/Japan
## installs tiles covering Japan

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/e130n30
git submodule init Objects/e140n30
git submodule init Objects/e140n40
git submodule init Terrain/e130n30
git submodule init Terrain/e140n30
git submodule init Terrain/e140n40

git submodule update Objects/e130n30
git submodule update Objects/e140n30
git submodule update Objects/e140n40
git submodule update Terrain/e130n30
git submodule update Terrain/e140n30
git submodule update Terrain/e140n40


