#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-s50
## installs tiles covering lat-s50

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e030s50
git submodule update --progress --init Objects/e050s50
git submodule update --progress --init Objects/e060s50
git submodule update --progress --init Objects/e070s50
git submodule update --progress --init Objects/e140s50
git submodule update --progress --init Objects/e160s50
git submodule update --progress --init Objects/e170s50
git submodule update --progress --init Objects/w010s50
git submodule update --progress --init Objects/w020s50
git submodule update --progress --init Objects/w070s50
git submodule update --progress --init Objects/w080s50
git submodule update --progress --init Objects/w180s50
git submodule update --progress --init Terrain/e030s50
git submodule update --progress --init Terrain/e050s50
git submodule update --progress --init Terrain/e060s50
git submodule update --progress --init Terrain/e070s50
git submodule update --progress --init Terrain/e140s50
git submodule update --progress --init Terrain/e160s50
git submodule update --progress --init Terrain/e170s50
git submodule update --progress --init Terrain/w010s50
git submodule update --progress --init Terrain/w020s50
git submodule update --progress --init Terrain/w070s50
git submodule update --progress --init Terrain/w080s50
git submodule update --progress --init Terrain/w180s50

