#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n50
## installs tiles covering lat-n50

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e000n50
git submodule update --progress --init Objects/e010n50
git submodule update --progress --init Objects/e020n50
git submodule update --progress --init Objects/e030n50
git submodule update --progress --init Objects/e040n50
git submodule update --progress --init Objects/e050n50
git submodule update --progress --init Objects/e060n50
git submodule update --progress --init Objects/e070n50
git submodule update --progress --init Objects/e080n50
git submodule update --progress --init Objects/e090n50
git submodule update --progress --init Objects/e100n50
git submodule update --progress --init Objects/e110n50
git submodule update --progress --init Objects/e120n50
git submodule update --progress --init Objects/e130n50
git submodule update --progress --init Objects/e140n50
git submodule update --progress --init Objects/e150n50
git submodule update --progress --init Objects/e160n50
git submodule update --progress --init Objects/e170n50
git submodule update --progress --init Objects/w010n50
git submodule update --progress --init Objects/w020n50
git submodule update --progress --init Objects/w040n50
git submodule update --progress --init Objects/w050n50
git submodule update --progress --init Objects/w060n50
git submodule update --progress --init Objects/w070n50
git submodule update --progress --init Objects/w080n50
git submodule update --progress --init Objects/w090n50
git submodule update --progress --init Objects/w100n50
git submodule update --progress --init Objects/w110n50
git submodule update --progress --init Objects/w120n50
git submodule update --progress --init Objects/w130n50
git submodule update --progress --init Objects/w140n50
git submodule update --progress --init Objects/w150n50
git submodule update --progress --init Objects/w160n50
git submodule update --progress --init Objects/w170n50
git submodule update --progress --init Objects/w180n50
git submodule update --progress --init Terrain/e000n50
git submodule update --progress --init Terrain/e010n50
git submodule update --progress --init Terrain/e020n50
git submodule update --progress --init Terrain/e030n50
git submodule update --progress --init Terrain/e040n50
git submodule update --progress --init Terrain/e050n50
git submodule update --progress --init Terrain/e060n50
git submodule update --progress --init Terrain/e070n50
git submodule update --progress --init Terrain/e080n50
git submodule update --progress --init Terrain/e090n50
git submodule update --progress --init Terrain/e100n50
git submodule update --progress --init Terrain/e110n50
git submodule update --progress --init Terrain/e120n50
git submodule update --progress --init Terrain/e130n50
git submodule update --progress --init Terrain/e140n50
git submodule update --progress --init Terrain/e150n50
git submodule update --progress --init Terrain/e160n50
git submodule update --progress --init Terrain/e170n50
git submodule update --progress --init Terrain/w010n50
git submodule update --progress --init Terrain/w020n50
git submodule update --progress --init Terrain/w040n50
git submodule update --progress --init Terrain/w050n50
git submodule update --progress --init Terrain/w060n50
git submodule update --progress --init Terrain/w070n50
git submodule update --progress --init Terrain/w080n50
git submodule update --progress --init Terrain/w090n50
git submodule update --progress --init Terrain/w100n50
git submodule update --progress --init Terrain/w110n50
git submodule update --progress --init Terrain/w120n50
git submodule update --progress --init Terrain/w130n50
git submodule update --progress --init Terrain/w140n50
git submodule update --progress --init Terrain/w150n50
git submodule update --progress --init Terrain/w160n50
git submodule update --progress --init Terrain/w170n50
git submodule update --progress --init Terrain/w180n50

