#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-s40
## installs tiles covering lat-s40

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --depth=1 --init Objects/e010s40
git submodule update --depth=1 --init Objects/e020s40
git submodule update --depth=1 --init Objects/e030s40
git submodule update --depth=1 --init Objects/e070s40
git submodule update --depth=1 --init Objects/e110s40
git submodule update --depth=1 --init Objects/e120s40
git submodule update --depth=1 --init Objects/e130s40
git submodule update --depth=1 --init Objects/e140s40
git submodule update --depth=1 --init Objects/e150s40
git submodule update --depth=1 --init Objects/e170s40
git submodule update --depth=1 --init Objects/w020s40
git submodule update --depth=1 --init Objects/w040s40
git submodule update --depth=1 --init Objects/w060s40
git submodule update --depth=1 --init Objects/w070s40
git submodule update --depth=1 --init Objects/w080s40
git submodule update --depth=1 --init Objects/w090s40
git submodule update --depth=1 --init Objects/w180s40
git submodule update --depth=1 --init Terrain/e010s40
git submodule update --depth=1 --init Terrain/e020s40
git submodule update --depth=1 --init Terrain/e030s40
git submodule update --depth=1 --init Terrain/e070s40
git submodule update --depth=1 --init Terrain/e110s40
git submodule update --depth=1 --init Terrain/e120s40
git submodule update --depth=1 --init Terrain/e130s40
git submodule update --depth=1 --init Terrain/e140s40
git submodule update --depth=1 --init Terrain/e150s40
git submodule update --depth=1 --init Terrain/e170s40
git submodule update --depth=1 --init Terrain/w020s40
git submodule update --depth=1 --init Terrain/w040s40
git submodule update --depth=1 --init Terrain/w060s40
git submodule update --depth=1 --init Terrain/w070s40
git submodule update --depth=1 --init Terrain/w080s40
git submodule update --depth=1 --init Terrain/w090s40
git submodule update --depth=1 --init Terrain/w180s40



