#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n00
## installs tiles covering lat-n00

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e000n00
git submodule update --progress --init Objects/e010n00
git submodule update --progress --init Objects/e020n00
git submodule update --progress --init Objects/e030n00
git submodule update --progress --init Objects/e040n00
git submodule update --progress --init Objects/e050n00
git submodule update --progress --init Objects/e070n00
git submodule update --progress --init Objects/e080n00
git submodule update --progress --init Objects/e090n00
git submodule update --progress --init Objects/e100n00
git submodule update --progress --init Objects/e110n00
git submodule update --progress --init Objects/e120n00
git submodule update --progress --init Objects/e130n00
git submodule update --progress --init Objects/e140n00
git submodule update --progress --init Objects/e150n00
git submodule update --progress --init Objects/e160n00
git submodule update --progress --init Objects/e170n00
git submodule update --progress --init Objects/w010n00
git submodule update --progress --init Objects/w020n00
git submodule update --progress --init Objects/w050n00
git submodule update --progress --init Objects/w060n00
git submodule update --progress --init Objects/w070n00
git submodule update --progress --init Objects/w080n00
git submodule update --progress --init Objects/w090n00
git submodule update --progress --init Objects/w100n00
git submodule update --progress --init Objects/w160n00
git submodule update --progress --init Objects/w170n00
git submodule update --progress --init Objects/w180n00
git submodule update --progress --init Terrain/e000n00
git submodule update --progress --init Terrain/e010n00
git submodule update --progress --init Terrain/e020n00
git submodule update --progress --init Terrain/e030n00
git submodule update --progress --init Terrain/e040n00
git submodule update --progress --init Terrain/e050n00
git submodule update --progress --init Terrain/e070n00
git submodule update --progress --init Terrain/e080n00
git submodule update --progress --init Terrain/e090n00
git submodule update --progress --init Terrain/e100n00
git submodule update --progress --init Terrain/e110n00
git submodule update --progress --init Terrain/e120n00
git submodule update --progress --init Terrain/e130n00
git submodule update --progress --init Terrain/e140n00
git submodule update --progress --init Terrain/e150n00
git submodule update --progress --init Terrain/e160n00
git submodule update --progress --init Terrain/e170n00
git submodule update --progress --init Terrain/w010n00
git submodule update --progress --init Terrain/w020n00
git submodule update --progress --init Terrain/w050n00
git submodule update --progress --init Terrain/w060n00
git submodule update --progress --init Terrain/w070n00
git submodule update --progress --init Terrain/w080n00
git submodule update --progress --init Terrain/w090n00
git submodule update --progress --init Terrain/w100n00
git submodule update --progress --init Terrain/w160n00
git submodule update --progress --init Terrain/w170n00
git submodule update --progress --init Terrain/w180n00

