#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n10
## installs tiles covering lat-n10

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/e000n10
git submodule init Objects/e010n10
git submodule init Objects/e020n10
git submodule init Objects/e030n10
git submodule init Objects/e040n10
git submodule init Objects/e050n10
git submodule init Objects/e070n10
git submodule init Objects/e080n10
git submodule init Objects/e090n10
git submodule init Objects/e100n10
git submodule init Objects/e110n10
git submodule init Objects/e120n10
git submodule init Objects/e130n10
git submodule init Objects/e140n10
git submodule init Objects/e160n10
git submodule init Objects/e170n10
git submodule init Objects/w010n10
git submodule init Objects/w020n10
git submodule init Objects/w030n10
git submodule init Objects/w060n10
git submodule init Objects/w070n10
git submodule init Objects/w080n10
git submodule init Objects/w090n10
git submodule init Objects/w100n10
git submodule init Objects/w110n10
git submodule init Objects/w120n10
git submodule init Objects/w150n10
git submodule init Objects/w160n10
git submodule init Objects/w170n10
git submodule init Terrain/e000n10
git submodule init Terrain/e010n10
git submodule init Terrain/e020n10
git submodule init Terrain/e030n10
git submodule init Terrain/e040n10
git submodule init Terrain/e050n10
git submodule init Terrain/e070n10
git submodule init Terrain/e080n10
git submodule init Terrain/e090n10
git submodule init Terrain/e100n10
git submodule init Terrain/e110n10
git submodule init Terrain/e120n10
git submodule init Terrain/e130n10
git submodule init Terrain/e140n10
git submodule init Terrain/e160n10
git submodule init Terrain/e170n10
git submodule init Terrain/w010n10
git submodule init Terrain/w020n10
git submodule init Terrain/w030n10
git submodule init Terrain/w060n10
git submodule init Terrain/w070n10
git submodule init Terrain/w080n10
git submodule init Terrain/w090n10
git submodule init Terrain/w100n10
git submodule init Terrain/w110n10
git submodule init Terrain/w120n10
git submodule init Terrain/w150n10
git submodule init Terrain/w160n10
git submodule init Terrain/w170n10

git submodule update Objects/e000n10
git submodule update Objects/e010n10
git submodule update Objects/e020n10
git submodule update Objects/e030n10
git submodule update Objects/e040n10
git submodule update Objects/e050n10
git submodule update Objects/e070n10
git submodule update Objects/e080n10
git submodule update Objects/e090n10
git submodule update Objects/e100n10
git submodule update Objects/e110n10
git submodule update Objects/e120n10
git submodule update Objects/e130n10
git submodule update Objects/e140n10
git submodule update Objects/e160n10
git submodule update Objects/e170n10
git submodule update Objects/w010n10
git submodule update Objects/w020n10
git submodule update Objects/w030n10
git submodule update Objects/w060n10
git submodule update Objects/w070n10
git submodule update Objects/w080n10
git submodule update Objects/w090n10
git submodule update Objects/w100n10
git submodule update Objects/w110n10
git submodule update Objects/w120n10
git submodule update Objects/w150n10
git submodule update Objects/w160n10
git submodule update Objects/w170n10
git submodule update Terrain/e000n10
git submodule update Terrain/e010n10
git submodule update Terrain/e020n10
git submodule update Terrain/e030n10
git submodule update Terrain/e040n10
git submodule update Terrain/e050n10
git submodule update Terrain/e070n10
git submodule update Terrain/e080n10
git submodule update Terrain/e090n10
git submodule update Terrain/e100n10
git submodule update Terrain/e110n10
git submodule update Terrain/e120n10
git submodule update Terrain/e130n10
git submodule update Terrain/e140n10
git submodule update Terrain/e160n10
git submodule update Terrain/e170n10
git submodule update Terrain/w010n10
git submodule update Terrain/w020n10
git submodule update Terrain/w030n10
git submodule update Terrain/w060n10
git submodule update Terrain/w070n10
git submodule update Terrain/w080n10
git submodule update Terrain/w090n10
git submodule update Terrain/w100n10
git submodule update Terrain/w110n10
git submodule update Terrain/w120n10
git submodule update Terrain/w150n10
git submodule update Terrain/w160n10
git submodule update Terrain/w170n10
