#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-s80
## installs tiles covering lat-s80

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --depth=1 --init Objects/e000s80
git submodule update --depth=1 --init Objects/e010s80
git submodule update --depth=1 --init Objects/e020s80
git submodule update --depth=1 --init Objects/e030s80
git submodule update --depth=1 --init Objects/e040s80
git submodule update --depth=1 --init Objects/e050s80
git submodule update --depth=1 --init Objects/e060s80
git submodule update --depth=1 --init Objects/e070s80
git submodule update --depth=1 --init Objects/e080s80
git submodule update --depth=1 --init Objects/e090s80
git submodule update --depth=1 --init Objects/e100s80
git submodule update --depth=1 --init Objects/e110s80
git submodule update --depth=1 --init Objects/e120s80
git submodule update --depth=1 --init Objects/e130s80
git submodule update --depth=1 --init Objects/e140s80
git submodule update --depth=1 --init Objects/e150s80
git submodule update --depth=1 --init Objects/e160s80
git submodule update --depth=1 --init Objects/e170s80
git submodule update --depth=1 --init Objects/w010s80
git submodule update --depth=1 --init Objects/w020s80
git submodule update --depth=1 --init Objects/w030s80
git submodule update --depth=1 --init Objects/w040s80
git submodule update --depth=1 --init Objects/w050s80
git submodule update --depth=1 --init Objects/w060s80
git submodule update --depth=1 --init Objects/w070s80
git submodule update --depth=1 --init Objects/w080s80
git submodule update --depth=1 --init Objects/w090s80
git submodule update --depth=1 --init Objects/w100s80
git submodule update --depth=1 --init Objects/w110s80
git submodule update --depth=1 --init Objects/w120s80
git submodule update --depth=1 --init Objects/w130s80
git submodule update --depth=1 --init Objects/w140s80
git submodule update --depth=1 --init Objects/w150s80
git submodule update --depth=1 --init Objects/w160s80
git submodule update --depth=1 --init Objects/w170s80
git submodule update --depth=1 --init Objects/w180s80
git submodule update --depth=1 --init Terrain/e000s80
git submodule update --depth=1 --init Terrain/e010s80
git submodule update --depth=1 --init Terrain/e020s80
git submodule update --depth=1 --init Terrain/e030s80
git submodule update --depth=1 --init Terrain/e040s80
git submodule update --depth=1 --init Terrain/e050s80
git submodule update --depth=1 --init Terrain/e060s80
git submodule update --depth=1 --init Terrain/e070s80
git submodule update --depth=1 --init Terrain/e080s80
git submodule update --depth=1 --init Terrain/e090s80
git submodule update --depth=1 --init Terrain/e100s80
git submodule update --depth=1 --init Terrain/e110s80
git submodule update --depth=1 --init Terrain/e120s80
git submodule update --depth=1 --init Terrain/e130s80
git submodule update --depth=1 --init Terrain/e140s80
git submodule update --depth=1 --init Terrain/e150s80
git submodule update --depth=1 --init Terrain/e160s80
git submodule update --depth=1 --init Terrain/e170s80
git submodule update --depth=1 --init Terrain/w010s80
git submodule update --depth=1 --init Terrain/w020s80
git submodule update --depth=1 --init Terrain/w030s80
git submodule update --depth=1 --init Terrain/w040s80
git submodule update --depth=1 --init Terrain/w050s80
git submodule update --depth=1 --init Terrain/w060s80
git submodule update --depth=1 --init Terrain/w070s80
git submodule update --depth=1 --init Terrain/w080s80
git submodule update --depth=1 --init Terrain/w090s80
git submodule update --depth=1 --init Terrain/w100s80
git submodule update --depth=1 --init Terrain/w110s80
git submodule update --depth=1 --init Terrain/w120s80
git submodule update --depth=1 --init Terrain/w130s80
git submodule update --depth=1 --init Terrain/w140s80
git submodule update --depth=1 --init Terrain/w150s80
git submodule update --depth=1 --init Terrain/w160s80
git submodule update --depth=1 --init Terrain/w170s80
git submodule update --depth=1 --init Terrain/w180s80


