#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n40
## installs tiles covering lat-n40

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --depth=1 --init Objects/e000n40
git submodule update --depth=1 --init Objects/e010n40
git submodule update --depth=1 --init Objects/e020n40
git submodule update --depth=1 --init Objects/e030n40
git submodule update --depth=1 --init Objects/e040n40
git submodule update --depth=1 --init Objects/e050n40
git submodule update --depth=1 --init Objects/e060n40
git submodule update --depth=1 --init Objects/e070n40
git submodule update --depth=1 --init Objects/e080n40
git submodule update --depth=1 --init Objects/e090n40
git submodule update --depth=1 --init Objects/e100n40
git submodule update --depth=1 --init Objects/e110n40
git submodule update --depth=1 --init Objects/e120n40
git submodule update --depth=1 --init Objects/e130n40
git submodule update --depth=1 --init Objects/e140n40
git submodule update --depth=1 --init Objects/e150n40
git submodule update --depth=1 --init Objects/w010n40
git submodule update --depth=1 --init Objects/w060n40
git submodule update --depth=1 --init Objects/w070n40
git submodule update --depth=1 --init Objects/w080n40
git submodule update --depth=1 --init Objects/w090n40
git submodule update --depth=1 --init Objects/w100n40
git submodule update --depth=1 --init Objects/w110n40
git submodule update --depth=1 --init Objects/w120n40
git submodule update --depth=1 --init Objects/w130n40
git submodule update --depth=1 --init Terrain/e000n40
git submodule update --depth=1 --init Terrain/e010n40
git submodule update --depth=1 --init Terrain/e020n40
git submodule update --depth=1 --init Terrain/e030n40
git submodule update --depth=1 --init Terrain/e040n40
git submodule update --depth=1 --init Terrain/e050n40
git submodule update --depth=1 --init Terrain/e060n40
git submodule update --depth=1 --init Terrain/e070n40
git submodule update --depth=1 --init Terrain/e080n40
git submodule update --depth=1 --init Terrain/e090n40
git submodule update --depth=1 --init Terrain/e100n40
git submodule update --depth=1 --init Terrain/e110n40
git submodule update --depth=1 --init Terrain/e120n40
git submodule update --depth=1 --init Terrain/e130n40
git submodule update --depth=1 --init Terrain/e140n40
git submodule update --depth=1 --init Terrain/e150n40
git submodule update --depth=1 --init Terrain/w010n40
git submodule update --depth=1 --init Terrain/w060n40
git submodule update --depth=1 --init Terrain/w070n40
git submodule update --depth=1 --init Terrain/w080n40
git submodule update --depth=1 --init Terrain/w090n40
git submodule update --depth=1 --init Terrain/w100n40
git submodule update --depth=1 --init Terrain/w110n40
git submodule update --depth=1 --init Terrain/w120n40
git submodule update --depth=1 --init Terrain/w130n40

