#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n80
## installs tiles covering lat-n80

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --depth=1 --init Objects/e000n80
git submodule update --progress --depth=1 --init Objects/e010n80
git submodule update --progress --depth=1 --init Objects/e020n80
git submodule update --progress --depth=1 --init Objects/e030n80
git submodule update --progress --depth=1 --init Objects/e040n80
git submodule update --progress --depth=1 --init Objects/e050n80
git submodule update --progress --depth=1 --init Objects/e060n80
git submodule update --progress --depth=1 --init Objects/e070n80
git submodule update --progress --depth=1 --init Objects/e080n80
git submodule update --progress --depth=1 --init Objects/e090n80
git submodule update --progress --depth=1 --init Objects/e100n80
git submodule update --progress --depth=1 --init Objects/e110n80
git submodule update --progress --depth=1 --init Objects/e120n80
git submodule update --progress --depth=1 --init Objects/e130n80
git submodule update --progress --depth=1 --init Objects/e140n80
git submodule update --progress --depth=1 --init Objects/e150n80
git submodule update --progress --depth=1 --init Objects/e160n80
git submodule update --progress --depth=1 --init Objects/e170n80
git submodule update --progress --depth=1 --init Objects/w010n80
git submodule update --progress --depth=1 --init Objects/w020n80
git submodule update --progress --depth=1 --init Objects/w030n80
git submodule update --progress --depth=1 --init Objects/w040n80
git submodule update --progress --depth=1 --init Objects/w050n80
git submodule update --progress --depth=1 --init Objects/w060n80
git submodule update --progress --depth=1 --init Objects/w070n80
git submodule update --progress --depth=1 --init Objects/w080n80
git submodule update --progress --depth=1 --init Objects/w090n80
git submodule update --progress --depth=1 --init Objects/w100n80
git submodule update --progress --depth=1 --init Objects/w110n80
git submodule update --progress --depth=1 --init Objects/w120n80
git submodule update --progress --depth=1 --init Objects/w130n80
git submodule update --progress --depth=1 --init Objects/w140n80
git submodule update --progress --depth=1 --init Objects/w150n80
git submodule update --progress --depth=1 --init Objects/w160n80
git submodule update --progress --depth=1 --init Objects/w170n80
git submodule update --progress --depth=1 --init Objects/w180n80
git submodule update --progress --depth=1 --init Terrain/e000n80
git submodule update --progress --depth=1 --init Terrain/e010n80
git submodule update --progress --depth=1 --init Terrain/e020n80
git submodule update --progress --depth=1 --init Terrain/e030n80
git submodule update --progress --depth=1 --init Terrain/e040n80
git submodule update --progress --depth=1 --init Terrain/e050n80
git submodule update --progress --depth=1 --init Terrain/e060n80
git submodule update --progress --depth=1 --init Terrain/e070n80
git submodule update --progress --depth=1 --init Terrain/e080n80
git submodule update --progress --depth=1 --init Terrain/e090n80
git submodule update --progress --depth=1 --init Terrain/e100n80
git submodule update --progress --depth=1 --init Terrain/e110n80
git submodule update --progress --depth=1 --init Terrain/e120n80
git submodule update --progress --depth=1 --init Terrain/e130n80
git submodule update --progress --depth=1 --init Terrain/e140n80
git submodule update --progress --depth=1 --init Terrain/e150n80
git submodule update --progress --depth=1 --init Terrain/e160n80
git submodule update --progress --depth=1 --init Terrain/e170n80
git submodule update --progress --depth=1 --init Terrain/w010n80
git submodule update --progress --depth=1 --init Terrain/w020n80
git submodule update --progress --depth=1 --init Terrain/w030n80
git submodule update --progress --depth=1 --init Terrain/w040n80
git submodule update --progress --depth=1 --init Terrain/w050n80
git submodule update --progress --depth=1 --init Terrain/w060n80
git submodule update --progress --depth=1 --init Terrain/w070n80
git submodule update --progress --depth=1 --init Terrain/w080n80
git submodule update --progress --depth=1 --init Terrain/w090n80
git submodule update --progress --depth=1 --init Terrain/w100n80
git submodule update --progress --depth=1 --init Terrain/w110n80
git submodule update --progress --depth=1 --init Terrain/w120n80
git submodule update --progress --depth=1 --init Terrain/w130n80
git submodule update --progress --depth=1 --init Terrain/w140n80
git submodule update --progress --depth=1 --init Terrain/w150n80
git submodule update --progress --depth=1 --init Terrain/w160n80
git submodule update --progress --depth=1 --init Terrain/w170n80
git submodule update --progress --depth=1 --init Terrain/w180n80


