#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n60
## installs tiles covering lat-n60

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --depth=1 --init Objects/e000n60
git submodule update --progress --depth=1 --init Objects/e010n60
git submodule update --progress --depth=1 --init Objects/e020n60
git submodule update --progress --depth=1 --init Objects/e030n60
git submodule update --progress --depth=1 --init Objects/e040n60
git submodule update --progress --depth=1 --init Objects/e050n60
git submodule update --progress --depth=1 --init Objects/e060n60
git submodule update --progress --depth=1 --init Objects/e070n60
git submodule update --progress --depth=1 --init Objects/e080n60
git submodule update --progress --depth=1 --init Objects/e090n60
git submodule update --progress --depth=1 --init Objects/e100n60
git submodule update --progress --depth=1 --init Objects/e110n60
git submodule update --progress --depth=1 --init Objects/e120n60
git submodule update --progress --depth=1 --init Objects/e130n60
git submodule update --progress --depth=1 --init Objects/e140n60
git submodule update --progress --depth=1 --init Objects/e150n60
git submodule update --progress --depth=1 --init Objects/e160n60
git submodule update --progress --depth=1 --init Objects/e170n60
git submodule update --progress --depth=1 --init Objects/w010n60
git submodule update --progress --depth=1 --init Objects/w020n60
git submodule update --progress --depth=1 --init Objects/w030n60
git submodule update --progress --depth=1 --init Objects/w040n60
git submodule update --progress --depth=1 --init Objects/w050n60
git submodule update --progress --depth=1 --init Objects/w060n60
git submodule update --progress --depth=1 --init Objects/w070n60
git submodule update --progress --depth=1 --init Objects/w080n60
git submodule update --progress --depth=1 --init Objects/w090n60
git submodule update --progress --depth=1 --init Objects/w100n60
git submodule update --progress --depth=1 --init Objects/w110n60
git submodule update --progress --depth=1 --init Objects/w120n60
git submodule update --progress --depth=1 --init Objects/w130n60
git submodule update --progress --depth=1 --init Objects/w140n60
git submodule update --progress --depth=1 --init Objects/w150n60
git submodule update --progress --depth=1 --init Objects/w160n60
git submodule update --progress --depth=1 --init Objects/w170n60
git submodule update --progress --depth=1 --init Objects/w180n60
git submodule update --progress --depth=1 --init Terrain/e000n60
git submodule update --progress --depth=1 --init Terrain/e010n60
git submodule update --progress --depth=1 --init Terrain/e020n60
git submodule update --progress --depth=1 --init Terrain/e030n60
git submodule update --progress --depth=1 --init Terrain/e040n60
git submodule update --progress --depth=1 --init Terrain/e050n60
git submodule update --progress --depth=1 --init Terrain/e060n60
git submodule update --progress --depth=1 --init Terrain/e070n60
git submodule update --progress --depth=1 --init Terrain/e080n60
git submodule update --progress --depth=1 --init Terrain/e090n60
git submodule update --progress --depth=1 --init Terrain/e100n60
git submodule update --progress --depth=1 --init Terrain/e110n60
git submodule update --progress --depth=1 --init Terrain/e120n60
git submodule update --progress --depth=1 --init Terrain/e130n60
git submodule update --progress --depth=1 --init Terrain/e140n60
git submodule update --progress --depth=1 --init Terrain/e150n60
git submodule update --progress --depth=1 --init Terrain/e160n60
git submodule update --progress --depth=1 --init Terrain/e170n60
git submodule update --progress --depth=1 --init Terrain/w010n60
git submodule update --progress --depth=1 --init Terrain/w020n60
git submodule update --progress --depth=1 --init Terrain/w030n60
git submodule update --progress --depth=1 --init Terrain/w040n60
git submodule update --progress --depth=1 --init Terrain/w050n60
git submodule update --progress --depth=1 --init Terrain/w060n60
git submodule update --progress --depth=1 --init Terrain/w070n60
git submodule update --progress --depth=1 --init Terrain/w080n60
git submodule update --progress --depth=1 --init Terrain/w090n60
git submodule update --progress --depth=1 --init Terrain/w100n60
git submodule update --progress --depth=1 --init Terrain/w110n60
git submodule update --progress --depth=1 --init Terrain/w120n60
git submodule update --progress --depth=1 --init Terrain/w130n60
git submodule update --progress --depth=1 --init Terrain/w140n60
git submodule update --progress --depth=1 --init Terrain/w150n60
git submodule update --progress --depth=1 --init Terrain/w160n60
git submodule update --progress --depth=1 --init Terrain/w170n60
git submodule update --progress --depth=1 --init Terrain/w180n60

