#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-s70
## installs tiles covering lat-s70

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --depth=1 --init Objects/e000s70
git submodule update --depth=1 --init Objects/e010s70
git submodule update --depth=1 --init Objects/e020s70
git submodule update --depth=1 --init Objects/e030s70
git submodule update --depth=1 --init Objects/e040s70
git submodule update --depth=1 --init Objects/e050s70
git submodule update --depth=1 --init Objects/e060s70
git submodule update --depth=1 --init Objects/e070s70
git submodule update --depth=1 --init Objects/e080s70
git submodule update --depth=1 --init Objects/e090s70
git submodule update --depth=1 --init Objects/e100s70
git submodule update --depth=1 --init Objects/e110s70
git submodule update --depth=1 --init Objects/e120s70
git submodule update --depth=1 --init Objects/e130s70
git submodule update --depth=1 --init Objects/e140s70
git submodule update --depth=1 --init Objects/e150s70
git submodule update --depth=1 --init Objects/e160s70
git submodule update --depth=1 --init Objects/e170s70
git submodule update --depth=1 --init Objects/w010s70
git submodule update --depth=1 --init Objects/w020s70
git submodule update --depth=1 --init Objects/w030s70
git submodule update --depth=1 --init Objects/w040s70
git submodule update --depth=1 --init Objects/w050s70
git submodule update --depth=1 --init Objects/w060s70
git submodule update --depth=1 --init Objects/w070s70
git submodule update --depth=1 --init Objects/w080s70
git submodule update --depth=1 --init Objects/w090s70
git submodule update --depth=1 --init Objects/w100s70
git submodule update --depth=1 --init Objects/w110s70
git submodule update --depth=1 --init Objects/w120s70
git submodule update --depth=1 --init Objects/w130s70
git submodule update --depth=1 --init Objects/w140s70
git submodule update --depth=1 --init Objects/w150s70
git submodule update --depth=1 --init Objects/w160s70
git submodule update --depth=1 --init Objects/w170s70
git submodule update --depth=1 --init Objects/w180s70
git submodule update --depth=1 --init Terrain/e000s70
git submodule update --depth=1 --init Terrain/e010s70
git submodule update --depth=1 --init Terrain/e020s70
git submodule update --depth=1 --init Terrain/e030s70
git submodule update --depth=1 --init Terrain/e040s70
git submodule update --depth=1 --init Terrain/e050s70
git submodule update --depth=1 --init Terrain/e060s70
git submodule update --depth=1 --init Terrain/e070s70
git submodule update --depth=1 --init Terrain/e080s70
git submodule update --depth=1 --init Terrain/e090s70
git submodule update --depth=1 --init Terrain/e100s70
git submodule update --depth=1 --init Terrain/e110s70
git submodule update --depth=1 --init Terrain/e120s70
git submodule update --depth=1 --init Terrain/e130s70
git submodule update --depth=1 --init Terrain/e140s70
git submodule update --depth=1 --init Terrain/e150s70
git submodule update --depth=1 --init Terrain/e160s70
git submodule update --depth=1 --init Terrain/e170s70
git submodule update --depth=1 --init Terrain/w010s70
git submodule update --depth=1 --init Terrain/w020s70
git submodule update --depth=1 --init Terrain/w030s70
git submodule update --depth=1 --init Terrain/w040s70
git submodule update --depth=1 --init Terrain/w050s70
git submodule update --depth=1 --init Terrain/w060s70
git submodule update --depth=1 --init Terrain/w070s70
git submodule update --depth=1 --init Terrain/w080s70
git submodule update --depth=1 --init Terrain/w090s70
git submodule update --depth=1 --init Terrain/w100s70
git submodule update --depth=1 --init Terrain/w110s70
git submodule update --depth=1 --init Terrain/w120s70
git submodule update --depth=1 --init Terrain/w130s70
git submodule update --depth=1 --init Terrain/w140s70
git submodule update --depth=1 --init Terrain/w150s70
git submodule update --depth=1 --init Terrain/w160s70
git submodule update --depth=1 --init Terrain/w170s70
git submodule update --depth=1 --init Terrain/w180s70

