#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n70
## installs tiles covering lat-n70

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e000n70
git submodule update --progress --init Objects/e010n70
git submodule update --progress --init Objects/e020n70
git submodule update --progress --init Objects/e030n70
git submodule update --progress --init Objects/e040n70
git submodule update --progress --init Objects/e050n70
git submodule update --progress --init Objects/e060n70
git submodule update --progress --init Objects/e070n70
git submodule update --progress --init Objects/e080n70
git submodule update --progress --init Objects/e090n70
git submodule update --progress --init Objects/e100n70
git submodule update --progress --init Objects/e110n70
git submodule update --progress --init Objects/e120n70
git submodule update --progress --init Objects/e130n70
git submodule update --progress --init Objects/e140n70
git submodule update --progress --init Objects/e150n70
git submodule update --progress --init Objects/e160n70
git submodule update --progress --init Objects/e170n70
git submodule update --progress --init Objects/w010n70
git submodule update --progress --init Objects/w020n70
git submodule update --progress --init Objects/w030n70
git submodule update --progress --init Objects/w040n70
git submodule update --progress --init Objects/w050n70
git submodule update --progress --init Objects/w060n70
git submodule update --progress --init Objects/w070n70
git submodule update --progress --init Objects/w080n70
git submodule update --progress --init Objects/w090n70
git submodule update --progress --init Objects/w100n70
git submodule update --progress --init Objects/w110n70
git submodule update --progress --init Objects/w120n70
git submodule update --progress --init Objects/w130n70
git submodule update --progress --init Objects/w140n70
git submodule update --progress --init Objects/w150n70
git submodule update --progress --init Objects/w160n70
git submodule update --progress --init Objects/w170n70
git submodule update --progress --init Objects/w180n70
git submodule update --progress --init Terrain/e000n70
git submodule update --progress --init Terrain/e010n70
git submodule update --progress --init Terrain/e020n70
git submodule update --progress --init Terrain/e030n70
git submodule update --progress --init Terrain/e040n70
git submodule update --progress --init Terrain/e050n70
git submodule update --progress --init Terrain/e060n70
git submodule update --progress --init Terrain/e070n70
git submodule update --progress --init Terrain/e080n70
git submodule update --progress --init Terrain/e090n70
git submodule update --progress --init Terrain/e100n70
git submodule update --progress --init Terrain/e110n70
git submodule update --progress --init Terrain/e120n70
git submodule update --progress --init Terrain/e130n70
git submodule update --progress --init Terrain/e140n70
git submodule update --progress --init Terrain/e150n70
git submodule update --progress --init Terrain/e160n70
git submodule update --progress --init Terrain/e170n70
git submodule update --progress --init Terrain/w010n70
git submodule update --progress --init Terrain/w020n70
git submodule update --progress --init Terrain/w030n70
git submodule update --progress --init Terrain/w040n70
git submodule update --progress --init Terrain/w050n70
git submodule update --progress --init Terrain/w060n70
git submodule update --progress --init Terrain/w070n70
git submodule update --progress --init Terrain/w080n70
git submodule update --progress --init Terrain/w090n70
git submodule update --progress --init Terrain/w100n70
git submodule update --progress --init Terrain/w110n70
git submodule update --progress --init Terrain/w120n70
git submodule update --progress --init Terrain/w130n70
git submodule update --progress --init Terrain/w140n70
git submodule update --progress --init Terrain/w150n70
git submodule update --progress --init Terrain/w160n70
git submodule update --progress --init Terrain/w170n70
git submodule update --progress --init Terrain/w180n70

