#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-s20
## installs tiles covering lat-s20

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e000s20
git submodule update --progress --init Objects/e010s20
git submodule update --progress --init Objects/e020s20
git submodule update --progress --init Objects/e030s20
git submodule update --progress --init Objects/e040s20
git submodule update --progress --init Objects/e050s20
git submodule update --progress --init Objects/e060s20
git submodule update --progress --init Objects/e070s20
git submodule update --progress --init Objects/e080s20
git submodule update --progress --init Objects/e090s20
git submodule update --progress --init Objects/e100s20
git submodule update --progress --init Objects/e110s20
git submodule update --progress --init Objects/e120s20
git submodule update --progress --init Objects/e130s20
git submodule update --progress --init Objects/e140s20
git submodule update --progress --init Objects/e150s20
git submodule update --progress --init Objects/e160s20
git submodule update --progress --init Objects/e170s20
git submodule update --progress --init Objects/w010s20
git submodule update --progress --init Objects/w020s20
git submodule update --progress --init Objects/w030s20
git submodule update --progress --init Objects/w040s20
git submodule update --progress --init Objects/w050s20
git submodule update --progress --init Objects/w060s20
git submodule update --progress --init Objects/w070s20
git submodule update --progress --init Objects/w080s20
git submodule update --progress --init Objects/w090s20
git submodule update --progress --init Objects/w100s20
git submodule update --progress --init Objects/w110s20
git submodule update --progress --init Objects/w120s20
git submodule update --progress --init Objects/w130s20
git submodule update --progress --init Objects/w140s20
git submodule update --progress --init Objects/w150s20
git submodule update --progress --init Objects/w160s20
git submodule update --progress --init Objects/w170s20
git submodule update --progress --init Objects/w180s20
git submodule update --progress --init Terrain/e000s20
git submodule update --progress --init Terrain/e010s20
git submodule update --progress --init Terrain/e020s20
git submodule update --progress --init Terrain/e030s20
git submodule update --progress --init Terrain/e040s20
git submodule update --progress --init Terrain/e050s20
git submodule update --progress --init Terrain/e060s20
git submodule update --progress --init Terrain/e070s20
git submodule update --progress --init Terrain/e080s20
git submodule update --progress --init Terrain/e090s20
git submodule update --progress --init Terrain/e100s20
git submodule update --progress --init Terrain/e110s20
git submodule update --progress --init Terrain/e120s20
git submodule update --progress --init Terrain/e130s20
git submodule update --progress --init Terrain/e140s20
git submodule update --progress --init Terrain/e150s20
git submodule update --progress --init Terrain/e160s20
git submodule update --progress --init Terrain/e170s20
git submodule update --progress --init Terrain/w010s20
git submodule update --progress --init Terrain/w020s20
git submodule update --progress --init Terrain/w030s20
git submodule update --progress --init Terrain/w040s20
git submodule update --progress --init Terrain/w050s20
git submodule update --progress --init Terrain/w060s20
git submodule update --progress --init Terrain/w070s20
git submodule update --progress --init Terrain/w080s20
git submodule update --progress --init Terrain/w090s20
git submodule update --progress --init Terrain/w100s20
git submodule update --progress --init Terrain/w110s20
git submodule update --progress --init Terrain/w120s20
git submodule update --progress --init Terrain/w130s20
git submodule update --progress --init Terrain/w140s20
git submodule update --progress --init Terrain/w150s20
git submodule update --progress --init Terrain/w160s20
git submodule update --progress --init Terrain/w170s20
git submodule update --progress --init Terrain/w180s20

