#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-n20
## installs tiles covering lat-n20

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --depth=1 --init Objects/e000n20
git submodule update --progress --depth=1 --init Objects/e010n20
git submodule update --progress --depth=1 --init Objects/e020n20
git submodule update --progress --depth=1 --init Objects/e030n20
git submodule update --progress --depth=1 --init Objects/e040n20
git submodule update --progress --depth=1 --init Objects/e050n20
git submodule update --progress --depth=1 --init Objects/e060n20
git submodule update --progress --depth=1 --init Objects/e070n20
git submodule update --progress --depth=1 --init Objects/e080n20
git submodule update --progress --depth=1 --init Objects/e090n20
git submodule update --progress --depth=1 --init Objects/e100n20
git submodule update --progress --depth=1 --init Objects/e110n20
git submodule update --progress --depth=1 --init Objects/e120n20
git submodule update --progress --depth=1 --init Objects/e130n20
git submodule update --progress --depth=1 --init Objects/e140n20
git submodule update --progress --depth=1 --init Objects/e150n20
git submodule update --progress --depth=1 --init Objects/w010n20
git submodule update --progress --depth=1 --init Objects/w020n20
git submodule update --progress --depth=1 --init Objects/w080n20
git submodule update --progress --depth=1 --init Objects/w090n20
git submodule update --progress --depth=1 --init Objects/w100n20
git submodule update --progress --depth=1 --init Objects/w110n20
git submodule update --progress --depth=1 --init Objects/w120n20
git submodule update --progress --depth=1 --init Objects/w160n20
git submodule update --progress --depth=1 --init Objects/w170n20
git submodule update --progress --depth=1 --init Objects/w180n20
git submodule update --progress --depth=1 --init Terrain/e000n20
git submodule update --progress --depth=1 --init Terrain/e010n20
git submodule update --progress --depth=1 --init Terrain/e020n20
git submodule update --progress --depth=1 --init Terrain/e030n20
git submodule update --progress --depth=1 --init Terrain/e040n20
git submodule update --progress --depth=1 --init Terrain/e050n20
git submodule update --progress --depth=1 --init Terrain/e060n20
git submodule update --progress --depth=1 --init Terrain/e070n20
git submodule update --progress --depth=1 --init Terrain/e080n20
git submodule update --progress --depth=1 --init Terrain/e090n20
git submodule update --progress --depth=1 --init Terrain/e100n20
git submodule update --progress --depth=1 --init Terrain/e110n20
git submodule update --progress --depth=1 --init Terrain/e120n20
git submodule update --progress --depth=1 --init Terrain/e130n20
git submodule update --progress --depth=1 --init Terrain/e140n20
git submodule update --progress --depth=1 --init Terrain/e150n20
git submodule update --progress --depth=1 --init Terrain/w010n20
git submodule update --progress --depth=1 --init Terrain/w020n20
git submodule update --progress --depth=1 --init Terrain/w080n20
git submodule update --progress --depth=1 --init Terrain/w090n20
git submodule update --progress --depth=1 --init Terrain/w100n20
git submodule update --progress --depth=1 --init Terrain/w110n20
git submodule update --progress --depth=1 --init Terrain/w120n20
git submodule update --progress --depth=1 --init Terrain/w160n20
git submodule update --progress --depth=1 --init Terrain/w170n20
git submodule update --progress --depth=1 --init Terrain/w180n20

