#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-s30
## installs tiles covering lat-s30

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/e010s30
git submodule init Objects/e020s30
git submodule init Objects/e030s30
git submodule init Objects/e040s30
git submodule init Objects/e050s30
git submodule init Objects/e110s30
git submodule init Objects/e120s30
git submodule init Objects/e130s30
git submodule init Objects/e140s30
git submodule init Objects/e150s30
git submodule init Objects/e160s30
git submodule init Objects/e170s30
git submodule init Objects/w030s30
git submodule init Objects/w050s30
git submodule init Objects/w060s30
git submodule init Objects/w070s30
git submodule init Objects/w080s30
git submodule init Objects/w090s30
git submodule init Objects/w110s30
git submodule init Objects/w130s30
git submodule init Objects/w140s30
git submodule init Objects/w150s30
git submodule init Objects/w160s30
git submodule init Objects/w180s30
git submodule init Terrain/e010s30
git submodule init Terrain/e020s30
git submodule init Terrain/e030s30
git submodule init Terrain/e040s30
git submodule init Terrain/e050s30
git submodule init Terrain/e110s30
git submodule init Terrain/e120s30
git submodule init Terrain/e130s30
git submodule init Terrain/e140s30
git submodule init Terrain/e150s30
git submodule init Terrain/e160s30
git submodule init Terrain/e170s30
git submodule init Terrain/w030s30
git submodule init Terrain/w050s30
git submodule init Terrain/w060s30
git submodule init Terrain/w070s30
git submodule init Terrain/w080s30
git submodule init Terrain/w090s30
git submodule init Terrain/w110s30
git submodule init Terrain/w130s30
git submodule init Terrain/w140s30
git submodule init Terrain/w150s30
git submodule init Terrain/w160s30
git submodule init Terrain/w180s30
git submodule update Objects/e010s30
git submodule update Objects/e020s30
git submodule update Objects/e030s30
git submodule update Objects/e040s30
git submodule update Objects/e050s30
git submodule update Objects/e110s30
git submodule update Objects/e120s30
git submodule update Objects/e130s30
git submodule update Objects/e140s30
git submodule update Objects/e150s30
git submodule update Objects/e160s30
git submodule update Objects/e170s30
git submodule update Objects/w030s30
git submodule update Objects/w050s30
git submodule update Objects/w060s30
git submodule update Objects/w070s30
git submodule update Objects/w080s30
git submodule update Objects/w090s30
git submodule update Objects/w110s30
git submodule update Objects/w130s30
git submodule update Objects/w140s30
git submodule update Objects/w150s30
git submodule update Objects/w160s30
git submodule update Objects/w180s30
git submodule update Terrain/e010s30
git submodule update Terrain/e020s30
git submodule update Terrain/e030s30
git submodule update Terrain/e040s30
git submodule update Terrain/e050s30
git submodule update Terrain/e110s30
git submodule update Terrain/e120s30
git submodule update Terrain/e130s30
git submodule update Terrain/e140s30
git submodule update Terrain/e150s30
git submodule update Terrain/e160s30
git submodule update Terrain/e170s30
git submodule update Terrain/w030s30
git submodule update Terrain/w050s30
git submodule update Terrain/w060s30
git submodule update Terrain/w070s30
git submodule update Terrain/w080s30
git submodule update Terrain/w090s30
git submodule update Terrain/w110s30
git submodule update Terrain/w130s30
git submodule update Terrain/w140s30
git submodule update Terrain/w150s30
git submodule update Terrain/w160s30
git submodule update Terrain/w180s30

