#!/bin/sh

## USAGE EXAMPLE
##
## install/lat-s60
## installs tiles covering lat-s60

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/e000s60
git submodule init Objects/e010s60
git submodule init Objects/e020s60
git submodule init Objects/e030s60
git submodule init Objects/e040s60
git submodule init Objects/e050s60
git submodule init Objects/e060s60
git submodule init Objects/e070s60
git submodule init Objects/e080s60
git submodule init Objects/e090s60
git submodule init Objects/e150s60
git submodule init Objects/e160s60
git submodule init Objects/w010s60
git submodule init Objects/w020s60
git submodule init Objects/w030s60
git submodule init Objects/w040s60
git submodule init Objects/w050s60
git submodule init Objects/w060s60
git submodule init Objects/w070s60
git submodule init Objects/w080s60
git submodule init Terrain/e000s60
git submodule init Terrain/e010s60
git submodule init Terrain/e020s60
git submodule init Terrain/e030s60
git submodule init Terrain/e040s60
git submodule init Terrain/e050s60
git submodule init Terrain/e060s60
git submodule init Terrain/e070s60
git submodule init Terrain/e080s60
git submodule init Terrain/e090s60
git submodule init Terrain/e150s60
git submodule init Terrain/e160s60
git submodule init Terrain/w010s60
git submodule init Terrain/w020s60
git submodule init Terrain/w030s60
git submodule init Terrain/w040s60
git submodule init Terrain/w050s60
git submodule init Terrain/w060s60
git submodule init Terrain/w070s60
git submodule init Terrain/w080s60

git submodule update Objects/e000s60
git submodule update Objects/e010s60
git submodule update Objects/e020s60
git submodule update Objects/e030s60
git submodule update Objects/e040s60
git submodule update Objects/e050s60
git submodule update Objects/e060s60
git submodule update Objects/e070s60
git submodule update Objects/e080s60
git submodule update Objects/e090s60
git submodule update Objects/e150s60
git submodule update Objects/e160s60
git submodule update Objects/w010s60
git submodule update Objects/w020s60
git submodule update Objects/w030s60
git submodule update Objects/w040s60
git submodule update Objects/w050s60
git submodule update Objects/w060s60
git submodule update Objects/w070s60
git submodule update Objects/w080s60
git submodule update Terrain/e000s60
git submodule update Terrain/e010s60
git submodule update Terrain/e020s60
git submodule update Terrain/e030s60
git submodule update Terrain/e040s60
git submodule update Terrain/e050s60
git submodule update Terrain/e060s60
git submodule update Terrain/e070s60
git submodule update Terrain/e080s60
git submodule update Terrain/e090s60
git submodule update Terrain/e150s60
git submodule update Terrain/e160s60
git submodule update Terrain/w010s60
git submodule update Terrain/w020s60
git submodule update Terrain/w030s60
git submodule update Terrain/w040s60
git submodule update Terrain/w050s60
git submodule update Terrain/w060s60
git submodule update Terrain/w070s60
git submodule update Terrain/w080s60
