#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-e170
## installs tiles covering lon-e170

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/e170n00
git submodule init Objects/e170n10
git submodule init Objects/e170n50
git submodule init Objects/e170n60
git submodule init Objects/e170n70
git submodule init Objects/e170n80
git submodule init Objects/e170s10
git submodule init Objects/e170s20
git submodule init Objects/e170s30
git submodule init Objects/e170s40
git submodule init Objects/e170s50
git submodule init Objects/e170s70
git submodule init Objects/e170s80
git submodule init Objects/e170s90
git submodule init Terrain/e170n00
git submodule init Terrain/e170n10
git submodule init Terrain/e170n50
git submodule init Terrain/e170n60
git submodule init Terrain/e170n70
git submodule init Terrain/e170n80
git submodule init Terrain/e170s10
git submodule init Terrain/e170s20
git submodule init Terrain/e170s30
git submodule init Terrain/e170s40
git submodule init Terrain/e170s50
git submodule init Terrain/e170s70
git submodule init Terrain/e170s80
git submodule init Terrain/e170s90

git submodule update Objects/e170n00
git submodule update Objects/e170n10
git submodule update Objects/e170n50
git submodule update Objects/e170n60
git submodule update Objects/e170n70
git submodule update Objects/e170n80
git submodule update Objects/e170s10
git submodule update Objects/e170s20
git submodule update Objects/e170s30
git submodule update Objects/e170s40
git submodule update Objects/e170s50
git submodule update Objects/e170s70
git submodule update Objects/e170s80
git submodule update Objects/e170s90
git submodule update Terrain/e170n00
git submodule update Terrain/e170n10
git submodule update Terrain/e170n50
git submodule update Terrain/e170n60
git submodule update Terrain/e170n70
git submodule update Terrain/e170n80
git submodule update Terrain/e170s10
git submodule update Terrain/e170s20
git submodule update Terrain/e170s30
git submodule update Terrain/e170s40
git submodule update Terrain/e170s50
git submodule update Terrain/e170s70
git submodule update Terrain/e170s80
git submodule update Terrain/e170s90
