#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-e120
## installs tiles covering lon-e120

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e120n00
git submodule update --progress --init Objects/e120n10
git submodule update --progress --init Objects/e120n20
git submodule update --progress --init Objects/e120n30
git submodule update --progress --init Objects/e120n40
git submodule update --progress --init Objects/e120n50
git submodule update --progress --init Objects/e120n60
git submodule update --progress --init Objects/e120n70
git submodule update --progress --init Objects/e120n80
git submodule update --progress --init Objects/e120s10
git submodule update --progress --init Objects/e120s20
git submodule update --progress --init Objects/e120s30
git submodule update --progress --init Objects/e120s40
git submodule update --progress --init Objects/e120s70
git submodule update --progress --init Objects/e120s80
git submodule update --progress --init Objects/e120s90
git submodule update --progress --init Terrain/e120n00
git submodule update --progress --init Terrain/e120n10
git submodule update --progress --init Terrain/e120n20
git submodule update --progress --init Terrain/e120n30
git submodule update --progress --init Terrain/e120n40
git submodule update --progress --init Terrain/e120n50
git submodule update --progress --init Terrain/e120n60
git submodule update --progress --init Terrain/e120n70
git submodule update --progress --init Terrain/e120n80
git submodule update --progress --init Terrain/e120s10
git submodule update --progress --init Terrain/e120s20
git submodule update --progress --init Terrain/e120s30
git submodule update --progress --init Terrain/e120s40
git submodule update --progress --init Terrain/e120s70
git submodule update --progress --init Terrain/e120s80
git submodule update --progress --init Terrain/e120s90

