#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-e130
## installs tiles covering lon-e130

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --depth=1 --init Objects/e130n00
git submodule update --depth=1 --init Objects/e130n10
git submodule update --depth=1 --init Objects/e130n20
git submodule update --depth=1 --init Objects/e130n30
git submodule update --depth=1 --init Objects/e130n40
git submodule update --depth=1 --init Objects/e130n50
git submodule update --depth=1 --init Objects/e130n60
git submodule update --depth=1 --init Objects/e130n70
git submodule update --depth=1 --init Objects/e130n80
git submodule update --depth=1 --init Objects/e130s10
git submodule update --depth=1 --init Objects/e130s20
git submodule update --depth=1 --init Objects/e130s30
git submodule update --depth=1 --init Objects/e130s40
git submodule update --depth=1 --init Objects/e130s70
git submodule update --depth=1 --init Objects/e130s80
git submodule update --depth=1 --init Objects/e130s90
git submodule update --depth=1 --init Terrain/e130n00
git submodule update --depth=1 --init Terrain/e130n10
git submodule update --depth=1 --init Terrain/e130n20
git submodule update --depth=1 --init Terrain/e130n30
git submodule update --depth=1 --init Terrain/e130n40
git submodule update --depth=1 --init Terrain/e130n50
git submodule update --depth=1 --init Terrain/e130n60
git submodule update --depth=1 --init Terrain/e130n70
git submodule update --depth=1 --init Terrain/e130n80
git submodule update --depth=1 --init Terrain/e130s10
git submodule update --depth=1 --init Terrain/e130s20
git submodule update --depth=1 --init Terrain/e130s30
git submodule update --depth=1 --init Terrain/e130s40
git submodule update --depth=1 --init Terrain/e130s70
git submodule update --depth=1 --init Terrain/e130s80
git submodule update --depth=1 --init Terrain/e130s90

