#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-w140
## installs tiles covering lon-w140 

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/w140n50
git submodule update --progress --init Objects/w140n60
git submodule update --progress --init Objects/w140n70
git submodule update --progress --init Objects/w140n80
git submodule update --progress --init Objects/w140s10
git submodule update --progress --init Objects/w140s20
git submodule update --progress --init Objects/w140s30
git submodule update --progress --init Objects/w140s70
git submodule update --progress --init Objects/w140s80
git submodule update --progress --init Objects/w140s90
git submodule update --progress --init Terrain/w140n50
git submodule update --progress --init Terrain/w140n60
git submodule update --progress --init Terrain/w140n70
git submodule update --progress --init Terrain/w140n80
git submodule update --progress --init Terrain/w140s10
git submodule update --progress --init Terrain/w140s20
git submodule update --progress --init Terrain/w140s30
git submodule update --progress --init Terrain/w140s70
git submodule update --progress --init Terrain/w140s80
git submodule update --progress --init Terrain/w140s90

