#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-w010
## installs tiles covering lon-w010

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --depth=1 --init Objects/w010n00
git submodule update --depth=1 --init Objects/w010n10
git submodule update --depth=1 --init Objects/w010n20
git submodule update --depth=1 --init Objects/w010n30
git submodule update --depth=1 --init Objects/w010n40
git submodule update --depth=1 --init Objects/w010n50
git submodule update --depth=1 --init Objects/w010n60
git submodule update --depth=1 --init Objects/w010n70
git submodule update --depth=1 --init Objects/w010n80
git submodule update --depth=1 --init Objects/w010s20
git submodule update --depth=1 --init Objects/w010s50
git submodule update --depth=1 --init Objects/w010s60
git submodule update --depth=1 --init Objects/w010s70
git submodule update --depth=1 --init Objects/w010s80
git submodule update --depth=1 --init Objects/w010s90
git submodule update --depth=1 --init Terrain/w010n00
git submodule update --depth=1 --init Terrain/w010n10
git submodule update --depth=1 --init Terrain/w010n20
git submodule update --depth=1 --init Terrain/w010n30
git submodule update --depth=1 --init Terrain/w010n40
git submodule update --depth=1 --init Terrain/w010n50
git submodule update --depth=1 --init Terrain/w010n60
git submodule update --depth=1 --init Terrain/w010n70
git submodule update --depth=1 --init Terrain/w010n80
git submodule update --depth=1 --init Terrain/w010s20
git submodule update --depth=1 --init Terrain/w010s50
git submodule update --depth=1 --init Terrain/w010s60
git submodule update --depth=1 --init Terrain/w010s70
git submodule update --depth=1 --init Terrain/w010s80
git submodule update --depth=1 --init Terrain/w010s90

