#!/bin/sh

## USAGE EXAMPLE
##
## install/w090
## installs tiles covering w090

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/w090n00
git submodule init Objects/w090n10
git submodule init Objects/w090n20
git submodule init Objects/w090n30
git submodule init Objects/w090n40
git submodule init Objects/w090n50
git submodule init Objects/w090n60
git submodule init Objects/w090n70
git submodule init Objects/w090n80
git submodule init Objects/w090s10
git submodule init Objects/w090s20
git submodule init Objects/w090s30
git submodule init Objects/w090s40
git submodule init Objects/w090s70
git submodule init Objects/w090s80
git submodule init Objects/w090s90
git submodule init Terrain/w090n00
git submodule init Terrain/w090n10
git submodule init Terrain/w090n20
git submodule init Terrain/w090n30
git submodule init Terrain/w090n40
git submodule init Terrain/w090n50
git submodule init Terrain/w090n60
git submodule init Terrain/w090n70
git submodule init Terrain/w090n80
git submodule init Terrain/w090s10
git submodule init Terrain/w090s20
git submodule init Terrain/w090s30
git submodule init Terrain/w090s40
git submodule init Terrain/w090s70
git submodule init Terrain/w090s80
git submodule init Terrain/w090s90

git submodule update Objects/w090n00
git submodule update Objects/w090n10
git submodule update Objects/w090n20
git submodule update Objects/w090n30
git submodule update Objects/w090n40
git submodule update Objects/w090n50
git submodule update Objects/w090n60
git submodule update Objects/w090n70
git submodule update Objects/w090n80
git submodule update Objects/w090s10
git submodule update Objects/w090s20
git submodule update Objects/w090s30
git submodule update Objects/w090s40
git submodule update Objects/w090s70
git submodule update Objects/w090s80
git submodule update Objects/w090s90
git submodule update Terrain/w090n00
git submodule update Terrain/w090n10
git submodule update Terrain/w090n20
git submodule update Terrain/w090n30
git submodule update Terrain/w090n40
git submodule update Terrain/w090n50
git submodule update Terrain/w090n60
git submodule update Terrain/w090n70
git submodule update Terrain/w090n80
git submodule update Terrain/w090s10
git submodule update Terrain/w090s20
git submodule update Terrain/w090s30
git submodule update Terrain/w090s40
git submodule update Terrain/w090s70
git submodule update Terrain/w090s80
git submodule update Terrain/w090s90
