#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-e110
## installs tiles covering lon-e110

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/e110n00
git submodule init Objects/e110n10
git submodule init Objects/e110n20
git submodule init Objects/e110n30
git submodule init Objects/e110n40
git submodule init Objects/e110n50
git submodule init Objects/e110n60
git submodule init Objects/e110n70
git submodule init Objects/e110n80
git submodule init Objects/e110s10
git submodule init Objects/e110s20
git submodule init Objects/e110s30
git submodule init Objects/e110s40
git submodule init Objects/e110s70
git submodule init Objects/e110s80
git submodule init Objects/e110s90
git submodule init Terrain/e110n00
git submodule init Terrain/e110n10
git submodule init Terrain/e110n20
git submodule init Terrain/e110n30
git submodule init Terrain/e110n40
git submodule init Terrain/e110n50
git submodule init Terrain/e110n60
git submodule init Terrain/e110n70
git submodule init Terrain/e110n80
git submodule init Terrain/e110s10
git submodule init Terrain/e110s20
git submodule init Terrain/e110s30
git submodule init Terrain/e110s40
git submodule init Terrain/e110s70
git submodule init Terrain/e110s80
git submodule init Terrain/e110s90

git submodule update Objects/e110n00
git submodule update Objects/e110n10
git submodule update Objects/e110n20
git submodule update Objects/e110n30
git submodule update Objects/e110n40
git submodule update Objects/e110n50
git submodule update Objects/e110n60
git submodule update Objects/e110n70
git submodule update Objects/e110n80
git submodule update Objects/e110s10
git submodule update Objects/e110s20
git submodule update Objects/e110s30
git submodule update Objects/e110s40
git submodule update Objects/e110s70
git submodule update Objects/e110s80
git submodule update Objects/e110s90
git submodule update Terrain/e110n00
git submodule update Terrain/e110n10
git submodule update Terrain/e110n20
git submodule update Terrain/e110n30
git submodule update Terrain/e110n40
git submodule update Terrain/e110n50
git submodule update Terrain/e110n60
git submodule update Terrain/e110n70
git submodule update Terrain/e110n80
git submodule update Terrain/e110s10
git submodule update Terrain/e110s20
git submodule update Terrain/e110s30
git submodule update Terrain/e110s40
git submodule update Terrain/e110s70
git submodule update Terrain/e110s80
git submodule update Terrain/e110s90
