#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-w030
## installs tiles covering lon-w030

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/w030n10
git submodule init Objects/w030n30
git submodule init Objects/w030n60
git submodule init Objects/w030n70
git submodule init Objects/w030n80
git submodule init Objects/w030s20
git submodule init Objects/w030s30
git submodule init Objects/w030s60
git submodule init Objects/w030s70
git submodule init Objects/w030s80
git submodule init Objects/w030s90
git submodule init Terrain/w030n10
git submodule init Terrain/w030n30
git submodule init Terrain/w030n60
git submodule init Terrain/w030n70
git submodule init Terrain/w030n80
git submodule init Terrain/w030s20
git submodule init Terrain/w030s30
git submodule init Terrain/w030s60
git submodule init Terrain/w030s70
git submodule init Terrain/w030s80
git submodule init Terrain/w030s90

git submodule update Objects/w030n10
git submodule update Objects/w030n30
git submodule update Objects/w030n60
git submodule update Objects/w030n70
git submodule update Objects/w030n80
git submodule update Objects/w030s20
git submodule update Objects/w030s30
git submodule update Objects/w030s60
git submodule update Objects/w030s70
git submodule update Objects/w030s80
git submodule update Objects/w030s90
git submodule update Terrain/w030n10
git submodule update Terrain/w030n30
git submodule update Terrain/w030n60
git submodule update Terrain/w030n70
git submodule update Terrain/w030n80
git submodule update Terrain/w030s20
git submodule update Terrain/w030s30
git submodule update Terrain/w030s60
git submodule update Terrain/w030s70
git submodule update Terrain/w030s80
git submodule update Terrain/w030s90
