#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-w080
## installs tiles covering lon-w080

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/w080n00
git submodule init Objects/w080n10
git submodule init Objects/w080n20
git submodule init Objects/w080n30
git submodule init Objects/w080n40
git submodule init Objects/w080n50
git submodule init Objects/w080n60
git submodule init Objects/w080n70
git submodule init Objects/w080n80
git submodule init Objects/w080s10
git submodule init Objects/w080s20
git submodule init Objects/w080s30
git submodule init Objects/w080s40
git submodule init Objects/w080s50
git submodule init Objects/w080s60
git submodule init Objects/w080s70
git submodule init Objects/w080s80
git submodule init Objects/w080s90
git submodule init Terrain/w080n00
git submodule init Terrain/w080n10
git submodule init Terrain/w080n20
git submodule init Terrain/w080n30
git submodule init Terrain/w080n40
git submodule init Terrain/w080n50
git submodule init Terrain/w080n60
git submodule init Terrain/w080n70
git submodule init Terrain/w080n80
git submodule init Terrain/w080s10
git submodule init Terrain/w080s20
git submodule init Terrain/w080s30
git submodule init Terrain/w080s40
git submodule init Terrain/w080s50
git submodule init Terrain/w080s60
git submodule init Terrain/w080s70
git submodule init Terrain/w080s80
git submodule init Terrain/w080s90

git submodule update Objects/w080n00
git submodule update Objects/w080n10
git submodule update Objects/w080n20
git submodule update Objects/w080n30
git submodule update Objects/w080n40
git submodule update Objects/w080n50
git submodule update Objects/w080n60
git submodule update Objects/w080n70
git submodule update Objects/w080n80
git submodule update Objects/w080s10
git submodule update Objects/w080s20
git submodule update Objects/w080s30
git submodule update Objects/w080s40
git submodule update Objects/w080s50
git submodule update Objects/w080s60
git submodule update Objects/w080s70
git submodule update Objects/w080s80
git submodule update Objects/w080s90
git submodule update Terrain/w080n00
git submodule update Terrain/w080n10
git submodule update Terrain/w080n20
git submodule update Terrain/w080n30
git submodule update Terrain/w080n40
git submodule update Terrain/w080n50
git submodule update Terrain/w080n60
git submodule update Terrain/w080n70
git submodule update Terrain/w080n80
git submodule update Terrain/w080s10
git submodule update Terrain/w080s20
git submodule update Terrain/w080s30
git submodule update Terrain/w080s40
git submodule update Terrain/w080s50
git submodule update Terrain/w080s60
git submodule update Terrain/w080s70
git submodule update Terrain/w080s80
git submodule update Terrain/w080s90
