#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-w100
## installs tiles covering lon-w100 

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/w100n00
git submodule update --progress --init Objects/w100n10
git submodule update --progress --init Objects/w100n20
git submodule update --progress --init Objects/w100n30
git submodule update --progress --init Objects/w100n40
git submodule update --progress --init Objects/w100n50
git submodule update --progress --init Objects/w100n60
git submodule update --progress --init Objects/w100n70
git submodule update --progress --init Objects/w100n80
git submodule update --progress --init Objects/w100s10
git submodule update --progress --init Objects/w100s20
git submodule update --progress --init Objects/w100s70
git submodule update --progress --init Objects/w100s80
git submodule update --progress --init Objects/w100s90
git submodule update --progress --init Terrain/w100n00
git submodule update --progress --init Terrain/w100n10
git submodule update --progress --init Terrain/w100n20
git submodule update --progress --init Terrain/w100n30
git submodule update --progress --init Terrain/w100n40
git submodule update --progress --init Terrain/w100n50
git submodule update --progress --init Terrain/w100n60
git submodule update --progress --init Terrain/w100n70
git submodule update --progress --init Terrain/w100n80
git submodule update --progress --init Terrain/w100s10
git submodule update --progress --init Terrain/w100s20
git submodule update --progress --init Terrain/w100s70
git submodule update --progress --init Terrain/w100s80
git submodule update --progress --init Terrain/w100s90

