#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-w180
## installs tiles covering lon-w180 

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --depth=1 --init Objects/w180n00
git submodule update --progress --depth=1 --init Objects/w180n20
git submodule update --progress --depth=1 --init Objects/w180n50
git submodule update --progress --depth=1 --init Objects/w180n60
git submodule update --progress --depth=1 --init Objects/w180n70
git submodule update --progress --depth=1 --init Objects/w180n80
git submodule update --progress --depth=1 --init Objects/w180s10
git submodule update --progress --depth=1 --init Objects/w180s20
git submodule update --progress --depth=1 --init Objects/w180s30
git submodule update --progress --depth=1 --init Objects/w180s40
git submodule update --progress --depth=1 --init Objects/w180s50
git submodule update --progress --depth=1 --init Objects/w180s70
git submodule update --progress --depth=1 --init Objects/w180s80
git submodule update --progress --depth=1 --init Objects/w180s90
git submodule update --progress --depth=1 --init Terrain/w180n00
git submodule update --progress --depth=1 --init Terrain/w180n20
git submodule update --progress --depth=1 --init Terrain/w180n50
git submodule update --progress --depth=1 --init Terrain/w180n60
git submodule update --progress --depth=1 --init Terrain/w180n70
git submodule update --progress --depth=1 --init Terrain/w180n80
git submodule update --progress --depth=1 --init Terrain/w180s10
git submodule update --progress --depth=1 --init Terrain/w180s20
git submodule update --progress --depth=1 --init Terrain/w180s30
git submodule update --progress --depth=1 --init Terrain/w180s40
git submodule update --progress --depth=1 --init Terrain/w180s50
git submodule update --progress --depth=1 --init Terrain/w180s70
git submodule update --progress --depth=1 --init Terrain/w180s80
git submodule update --progress --depth=1 --init Terrain/w180s90

