#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-w050
## installs tiles covering lon-w050

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule init Objects/w050n00
git submodule init Objects/w050n50
git submodule init Objects/w050n60
git submodule init Objects/w050n70
git submodule init Objects/w050n80
git submodule init Objects/w050s10
git submodule init Objects/w050s20
git submodule init Objects/w050s30
git submodule init Objects/w050s60
git submodule init Objects/w050s70
git submodule init Objects/w050s80
git submodule init Objects/w050s90
git submodule init Terrain/w050n00
git submodule init Terrain/w050n50
git submodule init Terrain/w050n60
git submodule init Terrain/w050n70
git submodule init Terrain/w050n80
git submodule init Terrain/w050s10
git submodule init Terrain/w050s20
git submodule init Terrain/w050s30
git submodule init Terrain/w050s60
git submodule init Terrain/w050s70
git submodule init Terrain/w050s80
git submodule init Terrain/w050s9

git submodule update Objects/w050n00
git submodule update Objects/w050n50
git submodule update Objects/w050n60
git submodule update Objects/w050n70
git submodule update Objects/w050n80
git submodule update Objects/w050s10
git submodule update Objects/w050s20
git submodule update Objects/w050s30
git submodule update Objects/w050s60
git submodule update Objects/w050s70
git submodule update Objects/w050s80
git submodule update Objects/w050s90
git submodule update Terrain/w050n00
git submodule update Terrain/w050n50
git submodule update Terrain/w050n60
git submodule update Terrain/w050n70
git submodule update Terrain/w050n80
git submodule update Terrain/w050s10
git submodule update Terrain/w050s20
git submodule update Terrain/w050s30
git submodule update Terrain/w050s60
git submodule update Terrain/w050s70
git submodule update Terrain/w050s80
git submodule update Terrain/w050s90
