#!/bin/sh

## USAGE EXAMPLE
##
## install/lon-e020
## installs tiles covering lon-e020

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/e020n00
git submodule update --progress --init Objects/e020n10
git submodule update --progress --init Objects/e020n20
git submodule update --progress --init Objects/e020n30
git submodule update --progress --init Objects/e020n40
git submodule update --progress --init Objects/e020n50
git submodule update --progress --init Objects/e020n60
git submodule update --progress --init Objects/e020n70
git submodule update --progress --init Objects/e020n80
git submodule update --progress --init Objects/e020s10
git submodule update --progress --init Objects/e020s20
git submodule update --progress --init Objects/e020s30
git submodule update --progress --init Objects/e020s40
git submodule update --progress --init Objects/e020s60
git submodule update --progress --init Objects/e020s70
git submodule update --progress --init Objects/e020s80
git submodule update --progress --init Objects/e020s90
git submodule update --progress --init Terrain/e020n00
git submodule update --progress --init Terrain/e020n10
git submodule update --progress --init Terrain/e020n20
git submodule update --progress --init Terrain/e020n30
git submodule update --progress --init Terrain/e020n40
git submodule update --progress --init Terrain/e020n50
git submodule update --progress --init Terrain/e020n60
git submodule update --progress --init Terrain/e020n70
git submodule update --progress --init Terrain/e020n80
git submodule update --progress --init Terrain/e020s10
git submodule update --progress --init Terrain/e020s20
git submodule update --progress --init Terrain/e020s30
git submodule update --progress --init Terrain/e020s40
git submodule update --progress --init Terrain/e020s60
git submodule update --progress --init Terrain/e020s70
git submodule update --progress --init Terrain/e020s80
git submodule update --progress --init Terrain/e020s90

