#!/bin/sh

## USAGE EXAMPLE
##
## install/SouthAmerica
## installs tiles covering SouthAmerica

# Copyright (C) 2016 IAHM-COL

#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Install any tile listed completely (initializing and updating both Terrain and Objects)

git submodule update --progress --init Objects/w030s60
git submodule update --progress --init Objects/w040s10
git submodule update --progress --init Objects/w040s20
git submodule update --progress --init Objects/w040s40
git submodule update --progress --init Objects/w040s60
git submodule update --progress --init Objects/w050n00
git submodule update --progress --init Objects/w050s10
git submodule update --progress --init Objects/w050s20
git submodule update --progress --init Objects/w050s30
git submodule update --progress --init Objects/w050s60
git submodule update --progress --init Objects/w060n00
git submodule update --progress --init Objects/w060s10
git submodule update --progress --init Objects/w060s20
git submodule update --progress --init Objects/w060s30
git submodule update --progress --init Objects/w060s40
git submodule update --progress --init Objects/w060s60
git submodule update --progress --init Objects/w070n00
git submodule update --progress --init Objects/w070n10
git submodule update --progress --init Objects/w070s10
git submodule update --progress --init Objects/w070s20
git submodule update --progress --init Objects/w070s30
git submodule update --progress --init Objects/w070s40
git submodule update --progress --init Objects/w070s50
git submodule update --progress --init Objects/w070s60
git submodule update --progress --init Objects/w080n00
git submodule update --progress --init Objects/w080n10
git submodule update --progress --init Objects/w080s10
git submodule update --progress --init Objects/w080s20
git submodule update --progress --init Objects/w080s30
git submodule update --progress --init Objects/w080s40
git submodule update --progress --init Objects/w080s50
git submodule update --progress --init Objects/w080s60
git submodule update --progress --init Objects/w090n00
git submodule update --progress --init Objects/w090s10
git submodule update --progress --init Objects/w090s20
git submodule update --progress --init Objects/w090s30
git submodule update --progress --init Objects/w090s40
git submodule update --progress --init Objects/w100n00
git submodule update --progress --init Objects/w100s10
git submodule update --progress --init Terrain/w030s60
git submodule update --progress --init Terrain/w040s10
git submodule update --progress --init Terrain/w040s20
git submodule update --progress --init Terrain/w040s40
git submodule update --progress --init Terrain/w040s60
git submodule update --progress --init Terrain/w050n00
git submodule update --progress --init Terrain/w050s10
git submodule update --progress --init Terrain/w050s20
git submodule update --progress --init Terrain/w050s30
git submodule update --progress --init Terrain/w050s60
git submodule update --progress --init Terrain/w060n00
git submodule update --progress --init Terrain/w060s10
git submodule update --progress --init Terrain/w060s20
git submodule update --progress --init Terrain/w060s30
git submodule update --progress --init Terrain/w060s40
git submodule update --progress --init Terrain/w060s60
git submodule update --progress --init Terrain/w070n00
git submodule update --progress --init Terrain/w070n10
git submodule update --progress --init Terrain/w070s10
git submodule update --progress --init Terrain/w070s20
git submodule update --progress --init Terrain/w070s30
git submodule update --progress --init Terrain/w070s40
git submodule update --progress --init Terrain/w070s50
git submodule update --progress --init Terrain/w070s60
git submodule update --progress --init Terrain/w080n00
git submodule update --progress --init Terrain/w080n10
git submodule update --progress --init Terrain/w080s10
git submodule update --progress --init Terrain/w080s20
git submodule update --progress --init Terrain/w080s30
git submodule update --progress --init Terrain/w080s40
git submodule update --progress --init Terrain/w080s50
git submodule update --progress --init Terrain/w080s60
git submodule update --progress --init Terrain/w090n00
git submodule update --progress --init Terrain/w090s10
git submodule update --progress --init Terrain/w090s20
git submodule update --progress --init Terrain/w090s30
git submodule update --progress --init Terrain/w090s40
git submodule update --progress --init Terrain/w100n00
git submodule update --progress --init Terrain/w100s10
 
